### ISSUE TITLE
How to resize height of DialogBox to fit content?

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#102]
![image](https://user-images.githubusercontent.com/92144641/215677456-b3823e45-297b-44e1-8b8e-54450ba58079.png)

Hi there, I have managed to fit a GUI onto the Duke logic, but when the Label in the DialogBox gets too long, it shows the rest as ellipsis.
May I know how to fix this?
I have tried searching online, but to no avail.

**Comment by hingen** [comment]
Try opening `DialogBox.fxml` in Scene Builder and change the min width and height of label to `USE_PREF_SIZE`

![image](https://user-images.githubusercontent.com/31367001/215681573-53eb1aa8-0a4c-45cb-969e-90d873150a36.png)

**Comment by Tempura-Person** [comment]
Strangely enough, it will seem alright as long as the command response isnt too large,
after which the thing glitches out.
For reference, what are your SceneBuilder size settings for the DialogBox?
I am using your Label size settings right now as reference.
![image](https://user-images.githubusercontent.com/92144641/215688716-41c37791-5d89-42da-9e39-4f1617e0b824.png)

**Comment by hingen** [comment]
In my `DialogBox.fxml`, I forced my HBox width to a fix value (590 in my case because I set my ScrollPane width in `MainWindow.fxml` to 590). Perhaps you can try setting it to a fix value as well.

![image](https://user-images.githubusercontent.com/31367001/215692074-acc433e1-d6f2-4176-b26c-89cd9fb818a0.png)

I'm not sure if my exact settings would be helpful as I've tweaked my `DialogBox.fxml` since I made my previous comment in order to fix an issue where the label exceeds the width of the window if a line of the text is too long. If you still want to reference my fxml files, I've already pushed all my commits to my repo, can look at them there.
