### ISSUE TITLE
Where did you use varargs?

### ISSUE THREAD

**Issue by angjunkang** [nus-cs2103-AY2223S2/forum#114]
Those of you who used varargs, where did you use them? Having learned about it in Week 4, I'd like to give it a go, but I haven't found a suitable use case yet. I was thinking, perhaps, it could be used for the find command, which can allow the program to take in multiple keywords simultaneously?

**Comment by dfordarius** [comment]
Hello, there are many possible ways to use the varargs, and you are definitely thinking in the right direction! I also used it to find multiple keywords. Just try it out theres no harm in doing so, jia you! 😄 

This was how i did it 

```
public findTaskMatchingKeywords(String ... keywords) {
      ...
}
```

**Comment by jundatan** [comment]
Hey! There are numerous ways to use the var-args. It is a method that takes in variable number of arguments. Hence, the name var-args. If you find any methods that require to take in a variable amount of arguments, that will be a suitable place to use it! Just like what @dfordarius said, there is no harm in trying with it. 😃

Edit:

```java
public String checkDescription(String... str) throws DukeException {
     ...
}
```
I have used it for mainly UI messages where i feel there is a need for extra text. Eg, sometimes you do not need the extra text in your UI messages methods and sometimes you want them to be added in.

**Comment by damithc** [comment]
@dfordarius @jundatan I think @Irminrics is asking where exactly did you guys use varargs in the iP (as you guys have pushed the `A-Varargs` tag).

**Comment by XylusChen** [comment]
Hi! I used var-args for my find command too! Specifially, I used a String type var-args parameter for the constructor of my FindCommand class. 

```
public FindCommand(String ... keywords) {
    ...
}
```

Like you mentioned, this allows users to search for tasks using multiple keywords, instead of just one keyword/phrase. Depending on how you want to implement the find command, you can return only tasks that matched all keywords or all tasks that matched with at least one keyword, or do both (will probably have to create another command for this to discern the distinct *find* behaviour). 👍 

Would be adviseable to inform users how your find command works so they won't be confused by the output.

**Comment by immanuelhume** [comment]
I created a bunch of delegates for `printf` on `Ui` instances, to produce an API similar to logging libraries.

```java
ui.info(String fmt, Object... args);
ui.error(String fmt, Object... args);
// etc etc, as needed
```

**Comment by muhammadreyaaz** [comment]
I used it to add multiple tasks and delete multiple tasks. Seems to be useful for the user to be able to do so. 

`TaskList<T> addMultipleTasks(Task... newTask) {...} `
`TaskList<T> removeMultipleTasks(int... index) {...}`

**Comment by angjunkang** [comment]
Thanks all! I got a good idea of how to implement it into my IP now.

**Comment by lhy-hoyin** [comment]
I know that @Irminrics have closed this issue, but I wanted to throw in my view since it seems slightly different from the the rest of the suggested usage.

So what I did was similar to how `public static void main(String ... args)` designed to be used. Essentially, it allows the end user to pass parameter when launching the application. What I did was to use to to allow user to set some flags to "control" the behavior of the program initialization.

```java
public static void main(String ... args) {
    // Process varargs for flags
    ArrayList<Flag> flags = processVarArgs(args);

    if (!flags.contains(Flag.SOME_CUSTOM_FLAG)) {
        // Do something as accordingly
    }

    // ...
}
```

What you use for the flags depends on how your Duke is implemented, and how you (intend) to use it. For me, I intend to make it such that it can have separate `TaskList` (e.g. to allow user to categorize their tasks). So I could have a ``--open "tasklist-name" flag to automatically open that the save file for that specific `TaskList`.

**Comment by BoAi01** [comment]
I use varargs for my `find` command. Specifically, it can take an arbitrary number of arguments, and it searches for potential matches in two cases:
1. Strong match: task string contains **all** input strings
2. Weak match: task string contains **at least one** input string

I implemented this for my `BCD-Extension` (week 5 task), i.e., `C-BetterSearch`.
