### ISSUE TITLE
Cyclic Dependency vs Bidirectional Navigability

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#119]
Hi all,

In the lecture notes, it seems like bidirectional navigability are accepted but does this not mean that there is a cyclic dependency between the 2 classes which is generally discouraged?

Also, just wanted to clarify the difference between bidirectional navigability and 2 uni-directional navigability pointing to each other between 2 classes. Lecture notes say that they are differnet but it would be great if someone could provide an example to show the differences!

**Comment by FredericChow00** [comment]
Upon further readings, it seems like bidirectional navigability are referring to the 2 classes having properties that are referencing to each other and that would be ok but cyclic dependency is more of passing the object as parameters in methods.

So does this mean that it would not be good to pass practice to pass in B as parameter to a method in A, while at the same timing passing in A to a method in B, but having the other class as a property would be ok because that is bidirectional navigability?

**Comment by damithc** [comment]
@FredericChow00 not a full answer but just a clarification:  
The diagram below says there is an association from `Foo` to `Bar` which means it goes without saying that `Foo` has a dependency on `Bar` (we don't show it as a `--->` because, well, it goes without saying :-). 

```mermaid
classDiagram
    Foo --> Bar
```

We use a `--->` only when there is no direct association from `Foo` to `Bar` but `Foo` still depends on `Bar` due to some other reason, such as `Foo` receives a `Bar` object as a parameter).

```mermaid
classDiagram
    Foo ..> Bar
```
We don't do the following because `-->` is redundant. 
```mermaid
classDiagram
    Foo --> Bar
    Foo ..> Bar
```

**Comment by FredericChow00** [comment]
@damithc Thank you for the clarification!

**Comment by damithc** [comment]
So, to restate some of the questions raised (correct me if I interpreted them wrong):

1. Does bi-directional navigability means a cyclic dependency?
2. Is bi-directional navigability acceptable or encouraged?
3. Is cyclic dependency acceptable or encouraged?
4. Are these two the same?

A:
```mermaid
classDiagram
    Foo --> Bar
    Foo <-- Bar
```

B:
```mermaid
classDiagram
    Foo <--> Bar
```

**Comment by FredericChow00** [comment]
Here are my preliminary answers (not sure if they are correct):

1. Since if navigable then associative, and if associative then dependent. So if bi-directional navigable then it's bi-dependent. Question is whether bi-dependent is equivalent to being cyclic dependent (Kind of the same question as Q4 which suggests that they are not the same thing). So my answer is no?

2. From lecture notes, it seems to be ok 

3. Not encouraged

4. No. Because two classes that have a bidirectional relationship suggests that Foo has a property that is specific to a particular Bar object and Bar has a property that is specific to the same Foo object (for the bottom picture). The top picture suggests that the two classes have 2 uni directional relationship which means that Foo has a property of type Bar (but can be any Bar object) and Bar has a property of type Foo (but can be any Foo object). 

So this means that while cyclic dependency is not encouraged, there are some cases where bi-directional navigability/association/dependenct is ok (for example Husband-Wife classes)

**Comment by FredericChow00** [comment]
@damithc hi prof, seems like there isn't much follow up on this. 

May I check if there are any misconceptions in my above answer?

**Comment by damithc** [comment]
@FredericChow00 thanks for the reminder. My answers below:

> 1\. Does bi-directional navigability means a cyclic dependency?

Yes. In both diagrams A and B (of question 4), each class has an implicit dependency on the other. For example, one class cannot be compiled without the other.

> 2\. Is bi-directional navigability acceptable or encouraged?

As usual, _it depends_. e.g., 
pro: it allows faster search/navigation through the object structure
con: more code and more space required to maintain the integrity of the references.
So it's a matter of which is more important to you in the given context.

> 3\. Is cyclic dependency acceptable or encouraged?

Dependencies in general are to be avoided as much as possible but sometime they are unavoidable.
It is impossible to have an OOP system with zero dependencies (because classes need to work with other classes).
Cyclic dependencies are even worse (and to be avoided even more) than regular dependencies. Still, sometimes they may be unavoidable.

> 4\. Are these two the same?

Your answer is correct.

**Comment by FredericChow00** [comment]
@damithc Ok thanks prof!
