### ISSUE TITLE
.idea folder keeps reappearing

### ISSUE THREAD

**Issue by elvern18** [nus-cs2103-AY2223S2/forum#120]
Level: A-Gradle

was following the Gradle tutorial to set up Gradle. Deleted .idea folder but it keeps reappearing for some reason, and I am unable to run Duke anymore (Project JDK not defined error appears, but even after setting JDK 11, still unable to run) 

![image](https://user-images.githubusercontent.com/77615600/216054608-a8e5b457-bb17-4c6a-9ab9-652a92a76408.png)

**Comment by damithc** [comment]
@elvern18 the purpose of deleting the .idea folder is simply to force Intellij to recreate it for Gradle. Therefore, the reappearance of .idea folder is expected. If you delete it again, Intellij will lose its settings, including the JDK setting.

**Comment by hingen** [comment]
As prof @damithc has mentioned, don't delete `.idea` again.

`.idea` is a directory that Intellij IDEA uses to store data specific to your project that it needs. So certain changes you make to your project such as setting the JDK to use as well as data on the version control used and build automation tool used is saved in it. Intellij IDEA needs the `.idea` directory to function correctly.

When you add gradle to your project, you delete `.idea` so that Intellij IDEA can generate a new `.idea` directory which is up-to-date with the changes (the files in `.idea` directory are now setup such that it is aware that gradle is being used for your project).

Hence, after you delete `.idea`, close the project, and reopen the project, don't delete `.idea` again. Do remember to setup the JDK version being used again though since that setting was deleted when the old `.idea` directory was deleted (in case you need the guide for setting your JDK version, [here](https://www.jetbrains.com/help/idea/sdk.html#set-up-jdk) it is.

**Comment by hingen** [comment]
On a side note, not sure if your repo changes are the most up-to-date but if it is, you might want to change the mainClassName in the `build.gradle` file.
```
application {
    mainClassName = "<name_of_package_containing_Duke.java>.Duke"
}
```

In your case, since you didn't place `Duke.java` in any package, it should probably be:
```
application {
    mainClassName = "Duke"
}
```
Remember to update later when you move `Duke.java` into a package.

**Comment by elvern18** [comment]
Thanks prof and @hingen for helping out ! I have changed the mainClassName to Duke and set the JDK version to jdk-11 already. However, when i run the Duke, upon the command "bye" the program exits and shows this error.

![image](https://user-images.githubusercontent.com/77615600/216375417-99d214e7-98fa-49af-8644-6c919cef30b2.png)



Appreciate if you can help me out once again. Thank you !

**Comment by joellow88** [comment]
> Thanks prof and @hingen for helping out ! I have changed the mainClassName to Duke and set the JDK version to jdk-11 already. However, when i run the Duke, upon the command "bye" the program exits and shows this error.
> 
> ![image](https://user-images.githubusercontent.com/77615600/216375417-99d214e7-98fa-49af-8644-6c919cef30b2.png)
> 
> Appreciate if you can help me out once again. Thank you !

I don't think this is a problem with gradle or the .idea folder anymore. Looking at your code, it seems that your save() function does not account for the case that the file specified does not exist. Can you check to see whether the duke.txt exists in the path you specified? If you have already created duke.txt, you might also want to check if the program runs in the ip directory or the parent folder of the ip directory. If it was the first case, then manually adding `File.separator + "ip"` is redundant.

**Comment by elvern18** [comment]
Oh yes it works now, didnt have this problem in the other levels. Thank you ! @joellow88
