### ISSUE TITLE
Issues when trying to import javafx

### ISSUE THREAD

**Issue by shittake** [nus-cs2103-AY2223S2/forum#121]
I am trying to setup javafx inside my code currently, and keep facing the following issue where I cannot import any of the symbols. Initially, it kept giving the error message `Error: JavaFX runtime components are missing, and are required to run this application` which I managed to fix by following the instructions under the "If you are not using Gradle" section. However, I still keep being unable to import the symbols as shown in the image below. Is anyone else facing a similar issue too?
![image](https://user-images.githubusercontent.com/40803540/216086257-aac526d9-7f4f-475c-b6a9-56d657e4c52c.png)

Additionally, I tried copying the code from the tutorial as shown:
``` java
import javafx.application.Application;

/** 
 * A launcher class to workaround classpath issues.
 */
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}
```
but I keep getting the following error message when I attempt to run the Launcher class:
![image](https://user-images.githubusercontent.com/40803540/216087177-7597acd1-9833-46a2-8792-6fb6232edeef.png)

As I followed the tutorial sequentially, I think the error could come from not being able to import the `Application` module in the first place as mentioned above. Any help would be appreciated, thanks!

**Comment by JunHao247** [comment]
@shittake Are you using Apple Silicon Macbook? I had the exact same problem and managed to solve it using the following link: https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html

Download and install the Azul build of OpenJDK 11 version, it supports fat JAR files and allows Apple Silicon Mac users to import javafx

**Comment by hingen** [comment]
Seems like you're experiencing multiple issues with different causes:

> `Error: JavaFX runtime components are missing, and are required to run this application`

Likely caused by placing the `main` method inside a class which extends `Application`. Can be resolved by creating a different class (e.g. `Launcher`) which contains the `main` method as you have already done.

> However, I still keep being unable to import the symbols as shown in the image below.

Perhaps try pressing the reload all gradle projects button
![image](https://user-images.githubusercontent.com/31367001/216192577-c1566e4e-71b6-45db-8eac-1b3f1e133bfa.png)

If all else fails, push all your code to your remote repo and clone to a different local directory. Hopefully when all the files in `.gitignore` are generated again, your issue would be resolved.

> but I keep getting the following error message when I attempt to run the Launcher class:
> ![image](https://user-images.githubusercontent.com/40803540/216087177-7597acd1-9833-46a2-8792-6fb6232edeef.png)

Likely caused by not having a default constructor in the `Duke` class. `Application.launch` requires that the class specified has a default constructor as that will be the constructor use to create the object. Try adding a constructor in `Duke` that doesn't take in any parameters and just have it call `super()`.

```java
public Duke() {
    super();
}
```

**Comment by shittake** [comment]
@hingen  Thank you for your help, having a default constructor in the `Duke` class did resolve the issue. For the first issue, I have no idea how, but when I came back to it after shutting down my laptop, it worked. Thanks!
