### ISSUE TITLE
Could not find or load main class duke.Launcher

### ISSUE THREAD

**Issue by chuakid** [nus-cs2103-AY2223S2/forum#126]
Development environment
* IntelliJ 2022.3.1
* Windows 11

I am having issues running the program through IntelliJ. **The program runs fine when I use gradle's `run` script** but when I run the program through IntelliJ's runner, it gives me an error.
```
Error: Could not find or load main class duke.Launcher
Caused by: java.lang.ClassNotFoundException: duke.Launcher
```

My duke.Launcher class is as follows:
```java
package duke;

import javafx.application.Application;

/**
 * Entry point
 */
class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}
```

Even more peculiar is that this error pops up even when I run the main method directly through the little green arrow next to the method itself.

![image](https://user-images.githubusercontent.com/12196891/216234431-adb29ae0-8056-46fc-b41a-45e442b5a40f.png)

**Comment by jamieeeleow** [comment]
I face a similar issue but instead got the error NoSuchMethodException

**Comment by Hongyi6328** [comment]
Hi, I am from your previous batch.

I guess Intellij cached a wrong/outdated path to the `Launcher`, can you try cleaning the cache like [this](https://stackoverflow.com/questions/17561826/how-to-clean-project-cache-in-intellij-idea-like-eclipses-clean)?

**Comment by damithc** [comment]
@chuakid While waiting for inputs from others, here are some things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by chuakid** [comment]
Deleting the .idea folder and then reimporting resolved the issue! Thanks for the help @Hongyi6328 and @damithc
