### ISSUE TITLE
Coding Standard For Switch Statements

### ISSUE THREAD

**Issue by 4ndrelim** [nus-cs2103-AY2223S2/forum#130]
The recommended form for switch statements is:
```
switch (condition) {
case ABC:
    statements;
case DEF:
    statements;
}
```
But if i wish to have a separate scope for each case statement, then the code would look something like the following:
```
switch (condition) {
case ABC: {
    statements;
}
case DEF: {
    statements;
}
}
```
Here, the closing curly braces for the last case statement is on the same level as that of the switch statement which is unpleasant to look at. I'm wondering if this in case, its fine to deviate from the coding standard (since it is just a guide) to improve readability.

**Comment by damithc** [comment]
@4ndrelim Avoid the need for scope if possible. In rare cases when it is needed, just follow the coding standard nevertheless as the only cost is just a bit of 'ugliness'. 
When following conventions, we try to avoid  introducing many 'exceptions' to the rules as such exceptions add to the overhead of following the convention (because everyone, even those not using scope, will need to know about the exception).

**Comment by 4ndrelim** [comment]
I see, will avoid in future instances, thanks prof! But if my existing code is similar to the latter, would it be fine leaving as such without incurring any penalty?

**Comment by damithc** [comment]
> I see, will avoid in future instances, thanks prof! But if my existing code is similar to the latter, would it be fine leaving as such without incurring any penalty?

@4ndrelim You can fix that in a future commit. :-) This comes under the topic of [refactoring](https://nus-cs2103-ay2223s2.github.io/website/schedule/week5/topics.html#w5-5-refactoring), which is covered in week 5 (today's lecture).

**Comment by 4ndrelim** [comment]
okay thanks prof!
