### ISSUE TITLE
Possible for Teammates tP links to be sent earlier?

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#135]
Hi Prof @damithc,

Is it possible for you to send out tP teammates submission links earlier in the week? Our group meets during the weekend and it would be beneficial to know what are the exact submission requirements that the module requires before we do the meeting.

Thanks!

**Comment by damithc** [comment]
@francisyzy All future TEAMMATES submissions are individual submissions that don't require a team discussion. Furthermore, the submission requirements are also given in the schedule page as well. For the 'product concept' submission that is currently ongoing, a description is there already (see below):
![image](https://user-images.githubusercontent.com/1673303/216661197-2ee9f54e-5b07-4a91-af4c-fc16a6047a7d.png)

Let me know if any critical information (that you need for the team meeting) is missing in the above so that I can add it next time.

**Comment by francisyzy** [comment]
Dear Prof, we were not aware that it was required to be written in 50 words and we wrote it in point form instead. I think including the format of submission can reduce the confusion faced by future teams!

Thanks!
