### ISSUE TITLE
Why doesn't source tree create branch?

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#136]
I have committed some changes on branch-A-assertions. I thought that source tree would create a separate branch from master but it did not?
![image](https://user-images.githubusercontent.com/78403168/216741024-e8fb7e2d-381b-4f38-99d6-03ada1a278b3.png)

**Comment by BoAi01** [comment]
I can see your `ip` repo has a branch named `branch-A-assertions`. Did you push to this branch instead of the `master` branch?

**Comment by hingen** [comment]
![image](https://user-images.githubusercontent.com/31367001/216741214-4c52569a-8895-487f-a783-d3c2fcee3ee3.png)

A bit confused on what you're asking. According to your image, there is a separate branch for `master` and `branch-A-Assertions` (according to the parts highlighted in red).

Forgive me if I misinterpret but perhaps what you're asking is why there is no split in the graph on the left (the blue line doesn't split into a different colour). That's because there isn't a need to. The graph on the left is merely a visual tool to make it clear which commit is on which branch.

In this case, since `master` has no commits made to it after the branching point, the graph doesn't split as the user can clearly make out which commits belong to `master` and which belongs to `branch-A-Assertions` purely base on the labels highlighted in red.

If both branches have commits made to them after the branching point, then the graph would split so as to make it clear which commit is on which branch.

**Comment by seadragon2000341** [comment]
thank you @hingen ! answered my qns nicely :)
I was also wondering why some of the blue circles are solid circles but one of them is hollow?

**Comment by hingen** [comment]
> I was also wondering why some of the blue circles are solid circles but one of them is hollow?

> ![image](https://user-images.githubusercontent.com/31367001/216741214-4c52569a-8895-487f-a783-d3c2fcee3ee3.png)

If you're referring to what I circled in green, that's just to indicate to you which commit you are currently on (the state of all your files in the project directory will match this commit). If I'm not wrong, in sourcetree you can double click a commit to go to it. This is called a git `checkout`.

If you make changes to your files, the hollow circle will move to a new entry in the graph called "Uncommited change". This isn't a commit but just sourcetree's way of telling you that the state of your current files are different from the commit that you were previously on.

**Comment by damithc** [comment]
> I have committed some changes on branch-A-assertions. I thought that source tree would create a separate branch from master but it did not?
> ![image](https://user-images.githubusercontent.com/78403168/216741024-e8fb7e2d-381b-4f38-99d6-03ada1a278b3.png)

@seadragon2000341 unless there are multiple parallel branches, SourceTree shows the history graph as a straight line even if there is a new branch on top of an existing branch.

Perhaps you were expecting to see this?
```
   o branch-x
   |
  /
 /
o master
|
o
|
o
```
But SourceTree shows it like this:
```
o branch-x
|
|
|
o master
|
o
|
o
```

**Comment by seadragon2000341** [comment]
Thank you all!

**Comment by adam07018** [comment]
I think it's because you don't have another branch going the other way. If you try to create a new branch based on master, it and commit, it will show like you expected

**Comment by Hikoya** [comment]
Hello @seadragon2000341 , I'm a senior from a previous batch, gentle reminder to close the issue if the problem has been resolved.
