### ISSUE TITLE
Will the post-lecture quiz marks be released only after the quiz is over?

### ISSUE THREAD

**Issue by anunayajoshi** [nus-cs2103-AY2223S2/forum#14]
For the week 1 pre-lecture quiz, we were able to see our marks after completing the quiz. 

We are not able to see it for week 2, and it states that "Correct answers and your score will be released within 1-2 days after the due date."

Is that intentional or do we need to wait for a while before we can see our marks, to check if we got above 70%?

Thank you!

**Comment by damithc** [comment]
> For the week 1 pre-lecture quiz, we were able to see our marks after completing the quiz.

@anunayajoshi That was a misconfiguration :-p Showing the score at the end causes many trial-and-error attempts which is not a productive use of time or a good way to learn. I've corrected the setting since then.
When doing the quiz, give it your best shot and without worrying about the score. It's not that hard to hit 70% for these quizzes.
The score and the correct answers will be revealed 1-2 days after the deadline.

**Comment by jiasheng59** [comment]
Even if the score is not shown, students can still do trial-and-error by trying different combinations of answers in multiple attempts in order to get higher (or full) marks. 

Since it's meant for students to check their understanding, I think there's no harm showing the score of an attempt. Moreover, showing score immediately will give students more timely feedback imho.

**Comment by damithc** [comment]
> Even if the score is not shown, students can still do trial-and-error by trying different combinations of answers in multiple attempts in order to get higher (or full) marks.

@jiasheng59 In theory yes, but unlikely this is worth the effort in practice. In any case, we can easily see if this happens as Canvas provides us the data. 

>Since it's meant for students to check their understanding, I think there's no harm showing the score of an attempt. Moreover, showing score immediately will give students more timely feedback imho. 

In some weeks, we want the quizzes, for some topics, we want students to know the answer immediately -- we have set those quizzes to show answer immediately. In most weeks, we want to have a gap between the trying and seeing the results, and try a bit harder at deciding on the right answer. More about why this is so will be in this week's lecture.
