### ISSUE TITLE
Unsure why my Launcher.main() is taking very long to run

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#142]
The application will still pop up after I run `Launcher.java` but I'm not sure what's with the lines of red code in the command line. Does anyone know what this mean?

<img width="1431" alt="Screenshot 2023-02-05 at 12 09 17 AM" src="https://user-images.githubusercontent.com/76247607/216777629-55c2d0ec-d122-4100-a38d-976d570da44e.png">

**Comment by pangrwa** [comment]
Is it because that my program is running? I notice that it's fine after I switch off the program.

**Comment by ExtraShotLatte** [comment]
Hi Rui Wei!

I tried looking into the issue (which don't really understand either, maybe others will have some idea?). 

`HIToolbox` is actually Apple's Human Interface (HI) Toolbox, a framework to handle UI. While I have no idea what is causing this error, finding related issues through Apple's [forums](https://discussions.apple.com/thread/677675) seems to suggest to me something along the lines of not handle User event or draw properly. 

[This post](https://developer.apple.com/forums/thread/724360) posted on Apple's forum two days ago seemed to be related, but no solution as well.

[This post](https://stackoverflow.com/questions/74609260/r-warnings-errors-in-a-fresh-install) on stackoverflow suggested success with setting the Menu Bar from "Never" back to "In Full Screen Only". Can you give this a try and report back? 😄 

Maybe someone who is more well versed with development on macOS can chip in?

**Comment by lyndonlim27** [comment]
Hi,

Not sure if this is correct but do check if you are running Azul build of OpenJDK 11
I have tried to find issues similar to this and what I have found so far is this might be caused by using the wrong java version.

**Comment by tituswe** [comment]
> 

Yes I know a few others who have ran into the issue because of this. 

Do the following steps to check:

**Check Version**
You can check by running 

`java --version`

in your terminal and your output should be as follows:

`openjdk version "11.0.17" 2022-10-18 LTS`
`OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)`
`OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)`

should you not see that you are using the Azul build then download it [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx)

**Check Location**
Then run 

`whereis java`

and your output should be `/usr/bin/java`

**Set `JAVA_HOME`** 
run

`nano ~/.bash_profile`

and add the following lines to the file:

`export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home`
`export JDK_HOME=$JAVA_HOME`
`export PATH=$PATH:$JAVA_HOME/bin`

save and exit the file then run

`source ~/.bash_profile` 

to reload the changes.

**Check**
run

`echo $JAVA_HOME`

you should see output

`/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home`

**END**

Hope this helps!!!

**Comment by adam07018** [comment]
Will there be same error if you do 100% same as the javafx tutorial?
