### ISSUE TITLE
Checkstyle IntelliJ giving error that cannot be resolved - does notm

### ISSUE THREAD

**Issue by WesleyBLDC** [nus-cs2103-AY2223S2/forum#151]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

Using IntelliJ with Java 11, with the same checkstyle file template provided in the cs2103 repo.

I get these two errors that I cannot resolve on the checkstyle, 

1) Name "Willy.ui" must match pattern....
2) Line matches the illegal pattern...

The exact error is in the screenshot.

May anyone advise what I can do? Or shall I ignore this?

:bulb
<img width="863" alt="SCR-20230209-l5pedited" src="https://user-images.githubusercontent.com/28299779/217744103-52931ba4-0e8c-4b2d-b125-7ceb5b6354ac.png">
: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by hingen** [comment]
1st error, probably change `Willy` to `willy`. The convention we are using is to use all lowercase for java packages. Do remember to rename the `Willy` directory as well.

2nd error, check if you have some additional spaces after `/**`. If so, remove them. If you're using Intellij IDEA, there is a setting that you can use to auto remove trailing whitespaces in your files. Can take a look [here](https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-auto-remove-trailing-spaces) if you're interested.

**Comment by damithc** [comment]
@WesleyBLDC Is the issue resolved? If so, you can close this issue. If no, post more details so that others can follow up.

**Comment by SPWwj** [comment]
The problem is caused by the name of your directory folder `Willy`.
Thus, your package name violates the check style convention.
Solution basically to rename your Willy folder using refactor function in IntelliJ Idea to `willy`.
![image](https://user-images.githubusercontent.com/30100720/218003333-7d2a6f06-d709-45fb-91c7-50128c2b6b0a.png)

Just a suggestion to check your treat Checkstyles error as warnings.
This allows you to run your app even you have style error.
Further it is good habits to resolve all the warnings.
![image](https://user-images.githubusercontent.com/30100720/218002704-b0ae92e4-a6af-4abd-b355-fe26e015c50e.png)

**Comment by WesleyBLDC** [comment]
Thanks everyone for your help.
