### ISSUE TITLE
Asking for suggestion: Where can I use assert in code

### ISSUE THREAD

**Issue by adam07018** [nus-cs2103-AY2223S2/forum#152]
I am very confused like where can I use assert? User input is different thus I shouldn't make assumption and assert anything right?

The only way I think about is to assert output string. Does it work in javaFX environment?

**Comment by SPWwj** [comment]
Assertions handle programmer's mistake.
First thing come into my mind is to use on the dependency class.
You may refer to my Parser.class.
Not a good design as I need to call specific functions before I can get the correct output.
However the assertion is quite useful in this situation as it can ensure I use my class correctly.
In addition, the exception is inappropriate to handle whether developer has use the function correctly.
Thus actually I should remove some of exceptions in my parser class XD.

**Comment by JamesLiuZX** [comment]
1. Assertions in Java are mainly used to help you debug during the development phase, such as checking the state/value of an object, or validity of arguments, passed for example into your Parser class. It should be as much as necessary to help you debug your core logic in where interactions between objects are involved, such as Parser and Storage. 

2. Assertions cannot be used to test graphical components such as JavaFX, as assertions are intended to test program logic and the state of variables, rather than the behavior or appearance of graphical elements. To test graphical components, you would typically use a testing framework that is specifically designed for that purpose, such as TestFX.

**Comment by Guo-KeCheng** [comment]
Assertion can be used:
- to check for things that are unlikely to happen unless there is something wrong in your code
- state things that you know are definitely true

Personally, I used it inside my switch-case
```
switch(input) {
case A:

case B:

default:
    assert false: "Should not reach here"; // Will not reach here
}
```

Here is a link I referred to before that you might find useful:
https://stackoverflow.com/questions/1957645/when-to-use-an-assertion-and-when-to-use-an-exception

**Comment by zhengsterz** [comment]
Personally i used my assertions to check for things like making sure that the size of my tasklist is more than -1 and generally checking that i havent messed up any of my own code

**Comment by hingen** [comment]
For me, I use it to check for whether the assumptions I made are fulfilled. When coding there are a lot of times where I make assumptions about the arguments I pass to my methods. For example:
```java
private void foo(String str) {
    return str.split(" ");
}
```

In this `foo(String)` method, there is an assumption that `str` is not null. Hence an assertion could be use to ensure `str` is not null. 

It helps in identifying errors and also, personally, I think of it as a good way to make it explicit the assumptions my method makes (especially for private methods where I don't write JavaDocs for).

**Comment by francisyzy** [comment]
Would like to ask if it is a good idea to use assert this way

```java
try {
       assert tasks.size() != 0 : "Hey, the list is empty!";
} catch (AssertionError e) {
       ui.showError(e);
}
```

Edit: never mind I read the stack overflow link above and don’t think its a good idea to use assertions. should use exceptions.

**Comment by SPWwj** [comment]
> For me, I use it to check for whether the assumptions I made are fulfilled. When coding there are a lot of times where I make assumptions about the arguments I pass to my methods. For example:
> 
> ```java
> 
> private void foo(String str) {
> 
>     return str.split(" ");
> 
> }
> 
> ```
> 
> 
> 
> In this `foo(String)` method, there is an assumption that `str` is not null. Hence an assertion could be use to ensure `str` is not null. 
> 
> 
> 
> It helps in identifying errors and also, personally, I think of it as a good way to make it explicit the assumptions my method makes (especially for private methods where I don't write JavaDocs for).

for our chatbot if the string input come from user，wouldn't it be too risky to use assertion as all the assertion will be disable during production environment🤔

**Comment by SPWwj** [comment]
> Personally i used my assertions to check for things like making sure that the size of my tasklist is more than -1 and generally checking that i havent messed up any of my own code

But the situation for -1 size list will never happen 😂

**Comment by hingen** [comment]
> for our chatbot if the string input come from user，wouldn't it be too risky to use assertion as all the assertion will be disable during production environment

Agreed, if we're handling user inputs, then exceptions should probably be used instead. The example I gave is just some arbitrary method meant to make the point that we often make assumptions in our code. It isn't a method I'd call with any kind of user input (at least not before running through some method to validate the input).

Perhaps, some might think that there's no point in having assertions in such cases by the following logic: "If the method does not take user input, then I have full control of the method arguments, thus I can always make sure that the arguments I pass in are always valid (fulfills the method's assumptions)."

But what's to say that someone else who takes over the code base is aware of these assumptions. And what's to say that the author of the code may not one day accidentally make a mistake and call the method without having the assumptions be fulfilled.

The goal of assertion, or at least the way I see it, is 2 folds:
1. It serves as a kind of "documentation", making it explicit what assumptions you have made so that another programmer or maybe even future you (as in the author of the code) would be able to remember the assumptions
2. It is for you to detect errors and also pinpoint the culprit line of code much more easily when you're doing unit testing, integration testing, UI testing, or manual testing. They should definitely not be enabled in the production build.

But yeah, just my opinion. Always happy to hear other's thoughts and perhaps also disagreements

**Comment by damithc** [comment]
> wouldn't it be too risky to use assertion as all the assertion will be disable during production environment

Yes, assertions should not be used to do any 'work' that is necessary for the operation of the application because assertions may not be enabled in production.





> The goal of assertion, or at least the way I see it, is 2 folds:
> 
> 1. It serves as a kind of "documentation", making it explicit what assumptions you have made so that another programmer or maybe even future you (as in the author of the code) would be able to remember the assumptions
> 2. It is for you to detect errors and also pinpoint the culprit line of code much more easily when you're doing unit testing, integration testing, UI testing, or manual testing. They should definitely not be enabled in the production build.

Correct. More specifically, '... to detect _programmer_ errors and also ...'
Also, assertions _can_ be enabled in production (especially in early versions) although it is not common.

**Comment by BoAi01** [comment]
@damithc @hingen Thank you for the great suggestions! The clarification is very clear.

**Comment by Hikoya** [comment]
Hello @adam07018 , I'm a senior from a previous batch, another gentle reminder to close the issue if your question has been answered satisfactory :) Else, please feel free to add in more details if you need more clarification.
