### ISSUE TITLE
Code quality - always possible to avoid long methods?

### ISSUE THREAD

**Issue by joellow88** [nus-cs2103-AY2223S2/forum#156]
From the textbook, 

> Be wary when a method is longer than the computer screen, and take corrective action when it goes beyond 30 LOC (lines of code). The bigger the haystack, the harder it is to find a needle.

I understand the intention behind this code quality guideline. However, I wonder whether there are cases in which having long methods are unavoidable and this guideline has to be disregarded. Or is it always possible to refactor long methods into a few shorter ones?

In my IP, I encountered some situations that I believe having long methods are unavoidable. Would like to know what others did to handle it, or if you would similarly violate the guideline.

**1. Switch case statements**
In a `handleCommand()` method, the different commands are checked using a switch-case statement. If the number of cases is large, would that necessitate an overly long `handleCommand()` method?

**2. JavaFX start method**
The `start()` method is called to start the GUI, and many of the required properties of the nodes on screen are defined there. If there are  many such properties or many such nodes, the `start()` method would easily go beyond the 30 lines guideline.

**Comment by damithc** [comment]
@joellow88 Code quality guidelines (unlike the coding standard) are subjective. So, you should exercise your own judgement when applying them. Yes, there are cases in which it's best not to follow them to the letter.

**Comment by BoAi01** [comment]
Just share a tip on avoiding if-else or switch statements, if that is desirable:
The following can directly instantiate a command object without branching
```
Class<?> c = Class.forName("command." + stringToCommandClassMap.get(command.split(" ")[0]));
Constructor<?> cons = c.getConstructor(String.class, boolean.class);
object = cons.newInstance(command, !suppressPrint);
``` 
where `stringToCommandClassMap` is a Hashmap that stores the pairs <user command keyword, command class name>, `cons.newInstance` calls the constructor, and `object` is a command class object which has an `execute` method.

**Comment by JamesLiuZX** [comment]
Hi. Just to add on a little further, there are fewer than 10 commands in our program, so a switch statement is fine as it is relatively readable and not exceedingly long. In the future when there are more tasks, like what @BoAi01 said we can use a Hashmap to map the commands to the methods. We can also store the commands in another package under duke.

Regarding the second point, I think for the rule of 30, code refactoring mainly serves to break down the complexity of the method into smaller manageable chunks, so it's more about making the logic less complex and more concise instead of reducing LOC. If there are many variables and components that you have to define regardless, then the 30 LOCs serves more as a guideline like what @damithc mentioned. 

Hope that helps.

**Comment by yyj-02** [comment]
In my opinion, I feel that as long as the code is easily readable and understandable, it is fine. The purpose of having good code quality is such that developers in the future can modify your code easily, which I think your code has fulfilled. However, in the case where there are more commands, i.e. `find`, `on`, ..., what we can do is categorise the commands into groups of commands according to their functionality. We can use nested routes, e.g. `add/event`, `add/deadline`, `search/on`, `search/find`, etc. With this format, we can use `switch ... case` for the first part of the route first and `switch ... case` the second part in another class. Hope this helps.
