### ISSUE TITLE
JavaFX not bundled into .jar file created

### ISSUE THREAD

**Issue by shittake** [nus-cs2103-AY2223S2/forum#160]
Hi everyone, 

I have followed the instructions in both [here](https://se-education.org/guides/tutorials/gradle.html#creating-a-jar-file) and in [here](https://openjfx.io/openjfx-docs/#gradle), but I am still not able to run my .jar file due to the same error `JavaFX runtime components are missing, and are required to run this application`. I understand this means that my JavaFX libraries are not bundled inside, but I am unsure what else I can do. I will really appreciate if someone who has faced a similar issue who can enlighten me on this, thanks!

I also have the error message: `Project : => no module-info.java found` every time I run my program locally. I'm not sure if this is a related issue, or a completely different issue.

Here is my [github repository](https://github.com/shittake/ip). Thanks in advance!

**Comment by damithc** [comment]
@shittake some additional info you can provide:
* Which OS are you using?
* What's the output for `java -version` command if you run it just before running the `java -jar JAR_FILE_NAME` command?

> I also have the error message: `Project : => no module-info.java found` every time I run my program locally. I'm not sure if this is a related issue, or a completely different issue.

This is not related, and can be ignored.

**Comment by MrTwit99** [comment]
Hi @shittake,

Here is something I realized while looking at your code.

![image](https://user-images.githubusercontent.com/97277438/218247125-1bac5078-00cf-40b5-b711-2d0313191a23.png)

Under your `build.gradle`, I believe you are giving the program the wrong file for mainClassName as shown here.

I believe in your case, your ``mainClassName`` should be ``Launcher`` instead of ``Duke`` as Launcher.java is the one starting your program / GUI? You might want to test again after changing that line.

**Comment by shittake** [comment]
Thank you for your replies! My Java version is 11.0.17 after running `java -version`.  Thanks @MrTwit99 for pointing that out - it now works well.
