### ISSUE TITLE
Advice on how to split up long replies by Duke

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#161]
Initially I tried to tackle this issue by tracking the number of lines that Duke replies and if the number of lines goes over a certian threshold, then I create a new dialogueContainer.

But that seems to not work in some cases. I feel like I should judge when to create a new dialogueContainer based on how long the replies are (like the height?) instead of how many sentences but I'm not sure how to do that

Any advice?

**Comment by damithc** [comment]
@FredericChow00 Could you share a screenshot of the GUI to illustrate the problem you are referring to?

**Comment by FredericChow00** [comment]
@damithc 

For the 4th task, theres more to the event "study" but it doesnt complete because the dialogueContainer is too small.
I'm trying to find a way such that the extra words would spill into the next dialogueContainer

![image](https://user-images.githubusercontent.com/108938188/218251697-4660a4f6-4948-4535-81da-b8b05fde28e0.png)

**Comment by weekiat-douze** [comment]
Hi, I believe it's because one of the dialog views have a fixed height. You can try to set it to "computed" via SceneBuilder if I'm not wrong.

**Comment by hingen** [comment]
Perhaps instead of creating a new `DialogBox`, you could consider having the `label` of `DialogBox.fxml` scale with the input. Not sure if [this](https://github.com/nus-cs2103-AY2223S2/forum/issues/102#issuecomment-1409829287) would allow you to do so since the way to do it depends on how your `fxml` is structured.

**Comment by jefrai** [comment]
It's difficult for the program to tell exactly which words are cut off - JavaFX doesn't provide a way to retrieve that info from its nodes. Instead, you might want to make the whole GUI resizable so that the user can drag it horizontally to see longer messages:

Try to resize your GUI as it is - some nodes should follow the new borders nicely, while others will stay stuck in their original positions.

![0Capture](https://user-images.githubusercontent.com/30693850/218272619-06b048fe-aef3-4f53-b672-999a4812dda9.PNG)

Select the stuck nodes in SceneBuilder, and bind their sides to the appropriate borders of the `AnchorPane`:

![2Capture](https://user-images.githubusercontent.com/30693850/218272815-146511ab-aec8-4efd-85e9-cd6825c0af82.png)

Some nodes in `DialogBox` might need to have their heights and widths changed as well. Once all nodes scale correctly, the GUI should be able to expand and display longer text.

![3Capture](https://user-images.githubusercontent.com/30693850/218273303-7b841efd-877d-47b2-8cb3-1e559ffc08a7.PNG)

**Comment by gwynethguo** [comment]
I have just encountered this problem. Try to use `TextFlow` instead of `Label`. If you still encounter problems regarding this, you can see the commits that I have pushed for A-BetterGui increment.

**Comment by toh-xinyi** [comment]
You can try setting the Min. height of the `Dialog Box` to `USE_PREF_SIZE`
![image](https://user-images.githubusercontent.com/121878184/218312552-3d876a24-3a43-4fd5-81f3-cfd7f0bb922c.png)
After doing that, for mine, the ellipses are gone and the remaining text shows. :)
Good luck!!

**Comment by SPWwj** [comment]
One alternative way is to use `dialog.setMinHeight();` to adjust the dialog text to the require height.
We can create two attributes to calculate the height width and height limit:
- `private static final int LINE_LIMIT = 45;`
- `private static final int LINE_HEIGHT = 30;`

Next just create a helper function to format the text:
` formatInput(String input) `
Then we can dynamically configure the dialogbox attritrube in its contructor.
`dialog.setMinHeight(dialogBoxInput.getLineNumber() * LINE_HEIGHT);`
You may refer to my code for more info.

**Comment by TabrizPlv** [comment]
It appears that you are using another `DialogBox` to account for lists that are too long. However, instead of creating another `DialogBox` you can actually scale the height of your `Label` so that it will stretch to fit events that are too long in length.
The approach to this is similar to the one mentioned by @toh-xinyi, but we apply it to the `Label` instead.
Refer to the Layout properties

![image](https://user-images.githubusercontent.com/85736132/218315227-d6ac8cc1-e1d8-4ff2-8ef1-8e084f3298eb.png)

**Comment by bryansendeavour** [comment]
Personally for Label I set USE_COMPUTED_SIZE for all as shown
<img width="650" alt="Screenshot 2023-02-13 at 12 49 57 PM" src="https://user-images.githubusercontent.com/97509884/218373371-68eec4af-b0f8-446f-9e38-665f763e7b4f.png">

this is the way long texts are shown
<img width="395" alt="Screenshot 2023-02-13 at 12 52 10 PM" src="https://user-images.githubusercontent.com/97509884/218373532-67c71cfb-e8e5-425d-9ca2-842cd95973c0.png">

**Comment by Hikoya** [comment]
Hello @FredericChow00  , I'm a senior from a previous batch, is there any updates to this issue? If the issue has been resolved, please remember to close the issue! :)
