### ISSUE TITLE
Master branch falling behind after merging PR

### ISSUE THREAD

**Issue by nerdyboy98** [nus-cs2103-AY2223S2/forum#162]
So I have been following the steps on the course website and realised the "master" branch was behind after completing the following steps:
1) Create pull request on github to merge A-CodeQuality to master
2) Approve the pull request (ticking create merge commit also)
3) Pulled the master branch to local repo by selecting "master" as the branch to pull

Asked my tp group about it and they had no idea as well. So I was wondering if this is normal and am I supposed to right-click on the master branch and select "merge master into current branch" to bring the master branch to the top? Thanks in advance!

![image](https://user-images.githubusercontent.com/110829473/218248971-49f28866-0df2-45f6-9ba4-d3ba303385ef.png)

**Comment by damithc** [comment]
@nerdyboy98 Not an answer but two tips:
* Tick the `[ ] Show Remote Branches` (shown in your screenshot) to see the status of the branches in your remote as well.
* In some cases, SoureTree UI doesn't show the latest status unless you press F5 to refresh the UI.
* You should switch to the `master` branch before pulling it. Otherwise the pulled master branch will get merged into the branch you are currently on (because pull = fetch + merge).

**Comment by nerdyboy98** [comment]
Hi prof, yup I had mistakenly did point number 3 and I went into master branch before pulling master branch. Now it seems that I have two A-CodeQuality branches with one having the "origin/" suffix as seen in the second image with Show Remote Branches ticked.
Is there any way to revert the wrong pull mentioned?

without "Show Remote Branches" ticked
![image](https://user-images.githubusercontent.com/110829473/218252736-3383312d-f857-4763-909e-fa1abead92df.png)

with "Show Remote Branches" ticked
![image](https://user-images.githubusercontent.com/110829473/218252631-413bff82-e878-46df-9abf-d922eca3c3bc.png)

**Comment by hingen** [comment]
Hi, trying to understand the issue here. If the issue is that you want to undo a local merge, that is revert the `branch-A-CodeQuality` branch to the commit before it merged into master branch, perhaps consider resetting your branch to the commit that `origin/branch-A-CodeQuality` is at.

To do so on sourcetree, perhaps look at the guide [here](https://confluence.atlassian.com/sourcetreekb/reset-branch-to-a-commit-788730897.html).

**Comment by francisyzy** [comment]
If your GitHub commits are all correct and you have no new changes that you want to keep in your local Git history, a quick way to solve it is to delete your local and clone again from Git.

**Comment by nerdyboy98** [comment]
@hingen ok I did what you mentioned I think its sorted already, thanks for the help guys!
