### ISSUE TITLE
How do you guys debug code when run from gradle?

### ISSUE THREAD

**Issue by szejiancheng** [nus-cs2103-AY2223S2/forum#173]
Currently encountering a bunch of unhelpful errors when attempting to run my code through gradle. Just wondering what others were doing when debugging with really unhelpful gradle stacktraces occupying most of the terminal.

**Comment by damithc** [comment]
@szejiancheng Perhaps you can share the full stack trace here so that others can have a better context about your situation?

**Comment by BoAi01** [comment]
In the Gradle error message, there are options to show full stack traces, which might be helpful. Just click the options and it will re-run the program.

**Comment by Hikoya** [comment]
Hello @szejiancheng  , I'm a senior from a previous batch, is there any updates to this issue? Please do share the stack traces here if you require help. Else, please remember to close the issue!

**Comment by jiasheng59** [comment]
I usually debug by using the CLI version of my application (I still keep the CLI's logic and related components in my code). I realize the errors thrown while using gradle are usually not shown in full sentence and it doesn't show which lines are involved. So I prefer to use the CLI version. In fact, you can make use of junit test also since common errors like ArrayIndexOutOfBound, NullPointerException usually involve only one or few methods.

**Comment by szejiancheng** [comment]
Followed @jiasheng59's advice! Closed!
