### ISSUE TITLE
Issue with creating JavaFX project in Gradle

### ISSUE THREAD

**Issue by daytona65** [nus-cs2103-AY2223S2/forum#175]
I am unable to create a new JavaFX project with Gradle, I created a new project just to do the JavaFX tutorial but I keep getting this error immediately:
![image](https://user-images.githubusercontent.com/74140641/218363942-9fdfe95d-be33-470f-bfba-cc3d2aadfcac.png)

The import statements for javafx also don't seem to work:
![image](https://user-images.githubusercontent.com/74140641/218364367-785cad11-38dc-4db8-8e5c-ddaf7c173674.png)

The build.gradle file seems to be greyed out as well:
![image](https://user-images.githubusercontent.com/74140641/218364622-1f46680f-8604-4ffc-a8f0-e4997d53ae89.png)

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try:
* Push the code to a pubic repo and share here so that other can try to replicate the problem.
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by homuntan02** [comment]
Hi daytona65, 
I also had similar issues and it was resolved after trying prof's first suggestion "File -> Invalidate caches".
Hope it resolves your issues too.

**Comment by damithc** [comment]
@daytona65 Is the issue resolved? If so, you can close this issue. If no, post more details so that others can follow up.
