### ISSUE TITLE
JavaFX error "The handle is invalid"

### ISSUE THREAD

**Issue by MrTwit99** [nus-cs2103-AY2223S2/forum#185]
Hi everyone,

I'm not sure what's causing the error for my JAR file but whenever i type the `bye` command, it always show me this error message.
![image](https://user-images.githubusercontent.com/97277438/218824854-8959ed0d-95a1-4a98-852c-6b2d4ecc51c8.png)

This error message does not happen when I run manually via my IDE as shown below.
![image](https://user-images.githubusercontent.com/97277438/218825016-dc625fb1-9139-46ef-b1ab-d18b4cc5a161.png)

Despite this error, my application does close as expected. AKA when i try to hit the next enter button, it will automatically close just as I set it to be. But I'm not sure if its now closing due to the error. 
Also, it is not printing my `bye` message hence the issue.

Notes:
I did create my JAR file via build.gradle > gradle runShadow
I tried running gradle shadowJar too
I did recreate my JAR file after all my implementations

**Comment by damithc** [comment]
@MrTwit99 While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

**Comment by MrTwit99** [comment]
Alright, thanks prof!

I have created a new branch "branch-InvalidHandleError" which can be accessed via this [link](https://github.com/MrTwit99/ip/tree/branch-InvalidHandleError)

I suspect the issue is probably at [duke.java](https://github.com/MrTwit99/ip/blob/branch-InvalidHandleError/src/main/java/duke/Duke.java)'s getResponse(). I'm not sure if there's any other thing to do to close the GUI but how i implemented the termination of Duke is via these two lines:
```java
Platform.exit();
System.exit(0);
```

**Comment by arkarsg** [comment]
I tried your `jar` file and has the behaviours as follows:

### Creates a data file
<img width="740" alt="Screenshot 2023-02-15 at 4 05 44 PM" src="https://user-images.githubusercontent.com/84555527/218968836-54add578-fb0e-4999-882a-bc5798ca9fc6.png">

### Shows quit message instead of `The handle is invalid`
![image](https://user-images.githubusercontent.com/84555527/218969090-14213310-7c50-4b72-97b8-428a38c8111a.png)

I also realised that some commands are still being printed on `System.out.println`

`The handle is invalid` is usually thrown by `IOException` so maybe that can be a start.

**Comment by PROGRAMMERHAO** [comment]
Hi! I downloaded the jar file and discovered the same thing. It is working fine.

<img width="687" alt="image" src="https://user-images.githubusercontent.com/88484192/218997331-51903f36-c359-4afa-a1d9-0935f0cdc48a.png">

**Comment by NBQian** [comment]
Seems like it depends on the java version you are using. I have the same error message when using java 11.0.17, but it works fine for java 11.0.18.

**Comment by MrTwit99** [comment]
i guess the issue lies with java version, thanks all!
