### ISSUE TITLE
Window not showing on Linux KDE

### ISSUE THREAD

**Issue by Beebeeoii** [nus-cs2103-AY2223S2/forum#186]
**Running: Manjaro KDE**

I am encountering an issue when if I have `stage.setResizable(false);` for my window, the window does not show up properly. Only a line is shown as shown below.

![image](https://user-images.githubusercontent.com/55170539/218907418-cec1732b-579a-4eb7-8d1d-55eb46d9d928.png)

This, however, works fine on macOS and Windows. There are no error messages. Not sure if anyone found any tricks to resolve this.

**Note:**
I have also tried launching AB3 (which shows up normally since the main window is resizable). However, the help window (which is not resizable) is also suffering from this issue.

## Some relevant issues:
https://github.com/nus-cs2103-AY2021S1/forum/issues/229
https://github.com/javafxports/openjdk-jfx/issues/222

**Comment by hingen** [comment]
I'm getting the same issue with the help window of AB3, it eventually resizes correctly if I open and close it multiple times. I'm also using KDE plasma (albeit on arch instead of manjaro) but haven't experience the issue with my IP.

Perhaps you could try setting the minWidth and minHeight of the stage?

Something like this:
```java
stage.setMinWidth(400.0);
stage.setMinHeight(600.0);
stage.setResizable(false);
```

**Comment by Beebeeoii** [comment]
thanks this works like a charm !
