### ISSUE TITLE
Unable to push to master after adding Ui.png on github and local refactoring

### ISSUE THREAD

**Issue by PROGRAMMERHAO** [nus-cs2103-AY2223S2/forum#195]
Hello I just made some commits directly on github to update the user guide and the Ui.png, following the instructions on the product website.

Now my sourceTree indicates that I have 5 pull updates. 

<img width="86" alt="image" src="https://user-images.githubusercontent.com/88484192/219306260-171fa6a4-38b7-429d-975d-9188d322f9b4.png">

However, after uploading my Ui.png I made some changes to my code locally and wish to push the code to the fork again. This time the sourceTree failed to push to the fork. May I ask if I need to pull first before pushing? Will my local changes be overwritten if I pull now? (By the way local changes have been committed)

The picture below is my error page when pushing
<img width="862" alt="image" src="https://user-images.githubusercontent.com/88484192/219306832-b1ed0bdb-4534-4bc2-bf82-dead8f04f108.png">
<img width="861" alt="image" src="https://user-images.githubusercontent.com/88484192/219306913-c41fbca2-cc2f-439b-8569-f346e902d05a.png">

Thanks for helping!

**Comment by Junyi00** [comment]
I believe your push is stopped because the remote repository has a different commit history compared to your local repository. Hence, pulling here would be necessary to update your local repository. 
Pulling in this case should not overwrite any changes you have made locally. If there are no conflicting changes, the pull should be seamless. In the event that there are conflicting changes, you would have to address them like you have practiced so during merging branches.

**Comment by PROGRAMMERHAO** [comment]
@Junyi00 Thank you so much for your comprehensive answer! Really appreciated.
