### ISSUE TITLE
Jar file does not run on Windows & Linux (JavaFX Dependencies)

### ISSUE THREAD

**Issue by tricixg** [nus-cs2103-AY2223S2/forum#198]
I am using M1 Mac with gradle 6.2 and openjdk version "11.0.18" 2023-01-17 LTS

As seen in the screenshot below, I think my problem is that when I refresh my gradle dependencies only the mac dependencies are "installed" as seen on the left under "external libraries". 

However, i can't seem to fix the issue and install the Linux and win dependencies. 

I have tried :
1. refreshing gradle dependancies 
2. cleaning my project by running `./gradlew clean` in the terminal, and then rebuilding it by running `./gradlew build.`

<img width="1440" alt="Screenshot 2023-02-17 at 10 42 06 AM" src="https://user-images.githubusercontent.com/64681919/219536218-8c3827c0-83b0-4f9d-b973-483575492191.png">

Ideally i think my external libraries should look like this.
![photo_2023-02-17 10 51 49](https://user-images.githubusercontent.com/64681919/219537647-5aef7dea-a4d0-4c7e-81cf-7c8e798988be.jpeg)

**Comment by jmestxr** [comment]
Hello, I'm also using M1 mac and I took a look at your build.gradle file. Just a guess, maybe you could **remove this block of code** from your **build.gradle** file:

```
javafx {
    version = "19"
    modules = [ 'javafx.controls' ]
}
```

and **replace** `String javaFxVersion = '19'` in 

```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'

    String javaFxVersion = '19'
    ...
} 
```

to **`String javaFxVersion = '11'`**.

Hope this might work.

**Comment by vigonometry** [comment]
I used `./gradlew build clean && ./gradlew build` to rebuild the project.
You may wish to refer to @jmestxr and set the javaFxVersion to 11

Additionally in your FXML files you should change the headers from `<fx:root...xmlns="http://javafx.com/javafx/19" xmlns:fx="http://javafx.com/fxml/1">` to `<fx:root...xmlns="http://javafx.com/javafx/" xmlns:fx="http://javafx.com/fxml/1">`.

I use an ARM processor too, you're recommended to install the Azul build as indicated in the warning.

**Comment by tituswe** [comment]
Hello @tricixg, 

You should install the Azul build of the the JDK, and make sure that your JDK and gradle versions are compatible! Not entirely sure but JDK 11 and gradle 6.2 may not work the best with each other. Here are the recommended setups!

<img width="832" alt="Screenshot 2023-02-17 at 1 20 16 PM" src="https://user-images.githubusercontent.com/97359862/219556341-161daa93-9f83-4dc5-8de4-7700c0decccb.png">

**Comment by 4ndrelim** [comment]
Hi, you may want to remove the openJDK version and install Java Azul version 11 as recommended by the guideline instead. I was previously using openJDK and everything was going fine (including the GUI portion, was able to run the steps in the advisory as well) so i thought it would work out fine. Yet, i faced similar issues with building the gradle and javafx and simply couldn't find a fix for it. Eventually i decided to just remove my existing version of java and replaced it with Azul. Below are links and tutorial i used to remove my openJDK and swap to Azul in case you decide to do so as well.

[Removing existing java](https://www.youtube.com/watch?v=wwV_L3lKYYw)
[How to change / set default java](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos) (i used this because i had java 17 installed as well)

All the best!

**Comment by tricixg** [comment]
> Hello, I'm also using M1 mac and I took a look at your build.gradle file. Just a guess, maybe you could **remove this block of code** from your **build.gradle** file:
> 
> ```
> javafx {
>     version = "19"
>     modules = [ 'javafx.controls' ]
> }
> ```
> 
> and **replace** `String javaFxVersion = '19'` in
> 
> ```
> dependencies {
>     testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
>     testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
> 
>     String javaFxVersion = '19'
>     ...
> } 
> ```
> 
> to **`String javaFxVersion = '11'`**.
> 
> Hope this might work.

this worked for me Thankyou!
