### ISSUE TITLE
Jar file does not have dependencies

### ISSUE THREAD

**Issue by runoutofit** [nus-cs2103-AY2223S2/forum#203]
I am using Intellij on windows, OpenJDK ver11.0.13 and gradle ver 6.2.

I am experiencing issues executing my jar file as it does not contain the dependencies.
I have attached a screenshot below in case my explanation is unclear.
![image](https://user-images.githubusercontent.com/97612129/219614556-6059616d-831d-4150-a5c0-401b7bb0b2c7.png)
By right the dependencies i have listed in my build.gradle file will appear there but currently it is empty. Any idea how to add the dependencies? I have tried running build dependents thus far but nothing changed.

**Comment by damithc** [comment]
@runoutofit While waiting for inputs from others, here are some things you can try:

* Try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
* Push the code to a branch and share here so that other can try to replicate the problem.

**Comment by EvitanRelta** [comment]
> I am experiencing issues executing my jar file as it does not contain the dependencies.

I'm assuming when u run the jar file, u get the error: `JavaFX runtime components are missing, and are required to run this application`? If so, it's likely similar to Issue #160.

I took a look at ur repo, and in ur `build.gradle` file, this was defined:

```bash
application {
    mainClassName = "seedu.duke.Duke"
}
```

Which I'm presuming was copied from the JavaFX tutorial. There's 2 things to address:
- The `seedu` in `seedu.duke.Duke` from the tutorial is just a placeholder package name, don't copy that.
- Instead of setting `Duke` in the `mainClassName`, it should be `Launcher` since the app needs to run the `Launcher::main` method, not `Duke::main`.

tdlr, just update ur `build.gradle` it to:

```bash
application {
    mainClassName = "duke.Launcher"
}
```

**Comment by runoutofit** [comment]
i changed the mainClassName locally already. The first jar file i built worked on my computer but not on others, but subsequent builds of my Jar file failed to run on my computer as well.
