### ISSUE TITLE
Unable to open JAR file on any laptop.

### ISSUE THREAD

**Issue by YZmunchmunch** [nus-cs2103-AY2223S2/forum#204]
I am using openJDK version 11.0.18, runtime environment Zulu11, and gradle version 7.6. I am able to build my jar file on intellij by running shadowJar, but when I am trying to open the jar file in terminal, this runtime error seems to occur. (JAR file name: AOT)

This is the error that i faced:
<img width="1172" alt="Screenshot 2023-02-17 at 8 02 31 PM" src="https://user-images.githubusercontent.com/86197080/219649730-18e4bde8-7d5c-4870-818b-551d2f1abb10.png">

Attach below is my build.gradle's plugins and dependencies

<img width="929" alt="Screenshot 2023-02-17 at 8 05 16 PM" src="https://user-images.githubusercontent.com/86197080/219650075-db8e73b8-b24d-4bd2-9354-b55d177ce62a.png">

es. Am i missing any code here? Seems that shadowJar works but opening the jar file seems to be an issue.

**Comment by francisyzy** [comment]
Try change 

```
application {
    mainClassName = "Munch"
}
```
To
```

application {
    mainClassName = "Munch.Launcher"
}

```

I had the same issue. It had to do with that chunk in build.gradle

**Comment by YZmunchmunch** [comment]
@francisyzy 
I tried making the above changes, but the error is
<img width="465" alt="Screenshot 2023-02-17 at 9 01 31 PM" src="https://user-images.githubusercontent.com/86197080/219659859-b0bbed52-3023-49cc-997c-a4984ea3de6e.png">

I sent my JAR file to 2 of my friends, one who is using windows, one using another mac m1. The windows one could work, the JAR file could be opened and my project could be run, but the mac one had the same issue with me. Thank you for your help tho.

**Comment by francisyzy** [comment]
Do u think it might be due to capitalization? From what I see in your repo, munich is lower caps right?

**Comment by chunzkok** [comment]
Hi! I was also facing this issue when my friend @WilliamHaiweiGu pointed me to the [relevant course page](https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html). Hope this works for you too!

In short, this is what I did:
1. Visit the [Azul website](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx), scroll down and download the .zip version
    - (you may wish to choose the `.dmg` file for the installer, I chose the `.zip` file as I didn't want to run Java 11 for all the other Java applications on my machine 💀 ) 
2. Unzip the file (or run the `.dmg`)
3. Use the `java` binary located under `<extraction-directory>/bin/` to run the jar file. (or just use `java` directly if you installed using the `.dmg` file, but you may have to check that it is referencing the correct java binary by following the steps in the mentioned course page)
    - example usage: `<extraction-directory>/bin/java -jar AOT.jar`

In case your command is extremely long like mine due to the extraction directory name, you can consider giving it an alias to make it easier to test these jar files:
1. Open `~/.zshrc` (can use `vim` or `nano` or your favourite text editor)
2. Add the following line (you can replace `java11` with any name you want):
    ```
    alias java11="<extraction-directory>/bin/java"
   ```
3. Restart your terminal, or reload the config file by entering
    ```
    source ~/.zshrc
    ```
5. Now you can run jar files using `java11 -jar AOT.jar`!

**Comment by seanfirefox** [comment]
Hi! For my Mac, somehow the java version from Azul was unable to compile the .jar file, and had the exact same error as you.
Instead, I used the `liberica` version that can be downloaded using Intellij.
You can go to `Project Structure > Project > SDK > Add SDK > Download JDK` and try.

<img width="513" alt="Screenshot 2023-02-20 at 10 45 45 AM" src="https://user-images.githubusercontent.com/35872524/219997826-4d6c1519-3d72-48a8-a4fd-38efad8fda84.png">

Hope this helps if the Azul version is not working.

If it still does not work, you can try swapping to all the different java versions provided by Intellij and test one by one, which was how I found the `liberica` version to be working for my Mac M1.

**Comment by NappySprout** [comment]
@chunzkok Thanks for the advice on running with a different java version it really helped! I was just wondering will you still pass the smoke test even if you use a different java version?

**Comment by damithc** [comment]
> I was just wondering will you still pass the smoke test even if you use a different java version?

@NappySprout it should be fine as long as you use the JDK mentioned in https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html to create/run the JAR.

**Comment by YZmunchmunch** [comment]
Hi, thanks for the help @chunzkok, however after implementing these methods, i am still facing the same problem. May i seek @damithc and @benedictchuajj 's assistance? Thank you!

**Comment by damithc** [comment]
@YZmunchmunch I suggest you push the code to a branch and share here so that other can try to replicate the problem.

**Comment by francisyzy** [comment]
I see that you've released your AOT.jar. I've downloaded it and it ran ok on my Mac, don’t have the class not found exception anymore.
