### ISSUE TITLE
Terminal outputs errors while running GUI. Will that be considered poor implementation?

### ISSUE THREAD

**Issue by fahim-tazz** [nus-cs2103-AY2223S2/forum#209]
I have a working GUI, but when trying to delete an index that does not exist, the terminal shows IndexOutOfBounds Exception. This does not break the GUI (it just display anything, and you can enter a different index to continue), the user can still use it properly. Will this impact grading?

**Comment by damithc** [comment]
@fahim-tazz Yes, it might, as this is not the correct behavior. Normally, one would expect to see an appropriate error message when the user enters an incorrect index.

**Comment by fahim-tazz** [comment]
Understood, Prof. Was asking because users aren't supposed to see terminal output, but I understand this project is not just about User Experience.
Thank you.

**Comment by damithc** [comment]
> Understood, Prof. Was asking because users aren't supposed to see terminal output, but I understand this project is not just about User Experience.

@fahim-tazz Based on your description, this is actually a UX issue caused by a problem in the code. The user-friendly behavior is for the user to be informed through the GUI that s/he typed an incorrect index. But it seems the error is not handled properly and only result in a user-unfriendly error message in the terminal -- the GUI simply does not show any response at all (right?). 

In addition, the terminal is still visible to the user (although the user is not required to be looking at it) and the output shown there should be reasonably 'clean' so that it does not cause unnecessary alarm to the user.
