### ISSUE TITLE
Errors while pushing a branch to a remote repo

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#21]
I am following the guide of pushing a branch to a remote repo [here](https://nus-cs2103-ay2223s2.github.io/website/schedule/week3/topics.html#W3-1), attached below. 

<img width="710" alt="Screenshot 2023-01-19 at 9 08 59 AM" src="https://user-images.githubusercontent.com/53465243/213331962-63755c37-4e10-4220-ac4d-59c4a10f5fc0.png">

Below is my `Sourcetree` configuration (M1 Mac) for pushing
<img width="1057" alt="Screenshot 2023-01-19 at 9 10 34 AM" src="https://user-images.githubusercontent.com/53465243/213332118-57825625-882c-4c61-8f32-d43699566a3f.png">

After clicking `OK`, it shows the following error
<img width="1054" alt="Screenshot 2023-01-19 at 9 10 57 AM" src="https://user-images.githubusercontent.com/53465243/213332159-e795b11d-996f-47e5-890a-8a2e0648bd1f.png">

What does the error mean?

**Comment by damithc** [comment]
@BoAi01 Try with a branch that doesn't have dashes in its name to see if that makes a difference. Also, try using the CLI commands instead of the SoureTree UI (you can click on the the `Terminal` button on the top right region of the SourceTree UI to open a terminal that you can use to enter CLI commands).
![image](https://user-images.githubusercontent.com/1673303/213339556-31fb3891-5e52-4b8b-92c5-3720d4c8fea1.png)

**Comment by BoAi01** [comment]
Thank you for the suggestion!

I figured out that the error was because the remote repo is not my fork but the original repo. Repeating these operations on my fork works fine.
