### ISSUE TITLE
Good practices and suggestions on structuring code to be clean and concise

### ISSUE THREAD

**Issue by rmj1405** [nus-cs2103-AY2223S2/forum#23]
Hi everyone,

I have abstracted the main logic for my chatbot into a `run()` method in a `ChatBot` class, and my approach to handling user queries is breaking the input down to a string array with _**{keyword}whitespace{command}**_ format which has resulted in me having a main if-else loop dependent on if its only a _keyword_ like "list" or _keyword and command_ like "uncheck 2" or "todo homework". However, within each condition I also have a switch statement for each keyword(uncheck, delete, etc) and my `run()` method has become quite long.

I am aware that I could possibly abstract each condition in the if-else into a separate class and shorten the method, but I am curious about other ways you have structured your main logic to be more clean and concise as well as any alternatives to using switch statements. I would love to hear your suggestions and ideas on improving code structure when there are many cases as in this chatbot! Thank you!

Attached is a snippet of my code for reference
```
else if(len == 2) {
      //cases: check 1, uncheck 2, event project meeting, etc
      //format: keyword{whitespace}command

      String fst = inputArr[0];
      String snd = inputArr[1];
      Boolean isNum = taskManager.isNumeric(snd);

      //if snd is numeric : cases are check/uncheck etc
      if(isNum) {
          int index = Integer.parseInt(snd) - 1;
          switch(fst) {
              case "check":
                  taskManager.checkTask(index);
                  break;
              case "uncheck":
                  taskManager.uncheckTask(index);
                  break;
              case "delete":
                  taskManager.deleteTask(index);
                  break;
              default:
                  System.out.println("I haven't learnt this command yet!\n" +
                          "Type menu to see the commands I know.");
                  break;
          }
      } else { //snd is a string input
          switch(fst) {
              case "todo":
                  ToDos todo = new ToDos(snd);
                  taskManager.addTaskToList(todo);
                  break;
              case "event":
```

**Comment by daitenshionyan** [comment]
Hello! I am unsure about the ideal way to implement this as well but here is what I am using. I think it reduces quite a significant amount of if-else checks.

A method that separates the command and arguments from the user input. The command will extracted and the arguments will be converted to a HashMap instead of a list. This way the command logic can just get whatever arguments it needs from the keywords and if it doesnt exist it can throw an exception that can be handled later on. With this, only the execution logic needs to be implemented.

```java
        String inputString = "";
        String command = "";

        try (Scanner scanner = new Scanner(rawInput)) {
            if (scanner.hasNext()) {
                command = scanner.getNext();
                if (scanner.hasNext()) {
                    inputString = scanner.nextLine().strip();
                }
            }
        }

        try {
            // convert to hash map
            HashMap<String, String> inputMap = parse(inputString);
            // execution
            switch(command) {
                case "deadline":
                    String by = Optional.ofNullable(inputMap.get("by"))
                        .orElseThrow(() -> new SomeSyntaxException("Missing by"));
                    // more logic
                    break;
                 // rest of the commands
                default:
                    // handle invalid commands
            }
        } catch (SomeSyntaxException syntaxEx) {
            // handle syntax errors
        } catch (SomeExecutionException executionEx) {
            // handle execution exeptions eg. index out of bounds
        }
```
By using a HashMap the user can enter the arguments in whatever order they want so long as the parameters are there (eg. `event /from mon /to fri` and `event /to fri /from mon` are the same). But all extra arguments (eg `todo qwer /qwer qwer`) will be ignored unless there are checks for them which might result in a lot of repeated code.

I broke the command execution logic in to separate classes to avoid a big switch block.

Hope this helps!!

**Comment by EvitanRelta** [comment]
I also used switch statements like u [@rmj1405](https://github.com/rmj1405), and also used hashmaps to separate the parameters from the `list`, `mark`, `delete` keywords like [@daitenshionyan](https://github.com/daitenshionyan).

I took it a step further, and off-loaded all these parsing of the commands to a class itself _(ie. `Command` class in the code snippet below)_, so that the `Duke.main` method is as clean as possible. Also, by moving the command-parsing-logic elsewhere, this adhere to the [SLAP recommendation](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard).

IMO, [@rmj1405](https://github.com/rmj1405) if u managed to combine the 2 switch-statements u have, into a single switch-statement, and abstract each command's out like what u did with `taskManager.checkTask`, `taskManager.deleteTask`, etc., it'll already be pretty clean.

```java
public static void main(String[] args) {
    // ... misc code

    Scanner scanner = new Scanner(System.in);
    TaskList tasks = new TaskList();
    
    while (true) {
        String input = scanner.nextLine();
        Command command = new Command(input);
    
        try {
            switch (command.keyword) {
                case "event":
                    Duke.addEvent(command, tasks);
                    break;
                case "mark":
                    Duke.mark(command, tasks);
                    break;
                case "list":
                    Duke.list(command, tasks);
                    break;
                
                // ... other keywords/commands
                
                default:
                    throw new DukeInvalidCommandException();
            }
        } catch (DukeException e) {
            // Handle exceptions.
        }
    }
    // ... misc code
}

private static void addEvent(Command command, TaskList tasks) throws DukeInvalidArgumentException {
    // ... error handling

    Task task = new TaskEvent(
        description, 
        command.argumentHashMapThing.get("from"), 
        command.argumentHashMapThing.get("to")
    );
    tasks.add(task);

    // ... misc code
}
```

**Comment by wxxedu** [comment]
My approach is kinda very wild. It may not be a good approach, and I over-engineered by quite a lot.

That said, I quite like it. So if you are interested, can have a look at the full code [[here](https://github.com/wxxedu/ip)](https://github.com/wxxedu/ip). (what I have written here is not exactly the same as what I have wrote in the actual code, as I have cleaned up things quite a bit there. That said, most of the idea is here.)

# Rationale

For me, I didn't use any `if`'s for this. The reason is that `if` and `switch` states are kind of hard to manage, especially if you want to add a feature later on. Every time you add a feature, you need to go through your files, and find out the locations where you used conditions to check. In most cases that I can think of, however, this shouldn’t be a problem (because you will most likely only have one top level keyword, i.e. delete, add, etc.). I was, however, kind of worried that if we were to do second-level instructions, and potentially 3 levels. For example, I was thinking:

```
task add hello world
```

where the first would indicate what module you are using, the second would be indicating the command that you are executing, and from the third word, it would be the actual message send to that command. 

Obviously, this approach isn’t very “iterative,” i.e. we should only be building the minimal to get the app started. But hey, I like over-engineering things… so…

One other disadvantage of using the `if` or `switch` statements is that they that would not provide any logical grouping for the different features. I do not want the mixing of different features. Ideally, on the very top level, I only want to use some very common interfaces and use  minimal code — so that, in the case that I want to rewrite some code for a specific feature, I would not have to interact with code for another feature at all. **This means that I want as much separation between different modules as possible**. 

# Basic Interfaces

## Executable

One thing that was pretty obvious to me from the very beginning is that everything looks like a “command,” hence abstracting them as a “command” sort of makes sense. However, since we don’t really need to have any predefined features for the “command,” it is more like an interface. Hence, I created the “Executable” interface, which defines the function `execute`.

```java
public interface Executable {
    ExitStatus execute(String[] tokens);
}
```

Let’s just leave the `ExitStatus` here, it’s a enum, it’s … a bit complicated and I don’t quite like it.

The input is firstly divided by the `" "` into different segments, which I call tokens, and then for any executable, it shall be able to execute on the tokens. This way, if we were to have second level subcommands as mentioned before, all we needed to do is to throw away the first item of the tokens, and then pass done the executables.

## IdentifiableExecutable

It would then became obvious that there are two types of commands: the commands that would be activated when no keywords are passed in, and the commands that would be activated when you pass in some keywords. For example, in the first task, we were asked to echo the command passed in:

```
> I love you.
I love you.
```

And for some tasks, like `bye` and `list`, where we were asked to identify what it is, and execute it accordingly. Hence, I defined another interface called `Identifiable` which has a getter for the id, the id being the keyword that’s needed for activating this command. Originally I was going to call it `Keywordable`, `Keyable`, etc. but they just sounded wrong lmao. 

```java
public interface Identifiable {
    public String getId();
}
```

And I created an interface extending both `Identifiable` and `Executable`, and called it `IdentifiableExecutable`. Maybe I could just put the `getId` into the `IdentifiableExecutable` and ignore the `Identifiable` interface all by itself, but I just did it this way. 

```java
public interface IdentifiableExecutable extends Identifiable, Executable {}
```

## NestableExecutableObject

Since my goal was to have the ease to support for nestable commands later one, we would need a tree-like structure. (I didn’t do this abstraction right away, it was while I was writing a more concrete class I realized that I could abstract this feature out). 

Firstly, this structure must be an `Executable`, so that when we call execute on the root tree, it would traverse down the execution, and we could use a set of unified interfaces for that.

Secondly, this structure would be able support both types of `Executable`'s as its children, i.e. it should be able to call `IdentifiableExecutable` if the `getId()` result of the instance matches the first token that’s passed in. To do this, I created a HashMap and a List inside this object:

```java
public class NestableExecutableObject implements Executable {
    // ... 
    private ArrayList<Executable> postExecutables;
    private HashMap<String, IdentifiableExecutable> identifiedExecutables;
    // ...
}
```

As their names do suggest, we should first handle the `identifiedExecutables`, after which we can deal with the `postExecutables`. And … since we are already complicating things to this extent, why not just add a preExecutables as well.

```java
public class NestableExecutableObject implements Executable {
    // ... 
    private ArrayList<Executable> preExecutables;
    private ArrayList<Executable> postExecutables;
    private HashMap<String, IdentifiableExecutable> identifiedExecutables;
    // ...
}
```

Further, we need “setters” for this executable fields as well. The word “register” sounds very cool to me, so I wrote three “setters”: 

```java
public class NestableExecutableObject implements Executable {
    // ...
    void registerPreExecutable(Executable executable) {
        // code to add the executable to the preExecutables
    }
    void registerPostExecutable(Executable executable) {
        // code to add the executable to the preExecutables
    }
    void registerIdentifiedExecutable(IdentifiableExecutable executable) {
        final String key = executable.getId();
        // put the key, executable into the identifiedExecutable hashmap
    }
    // ...
}
```

And, it would be very reasonable, for any command, to run through the `preExecutables` first, then the `identifiedExecutables` whose key matched the first token of the tokens (remember our `Executable` interface?), and lastly, the `postExecutables`.

## ExitStatus

Now we have a problem: after running an executable for a single command (tokens array), there may be cases where it want a second executable to run using the same command, or it would simply want this command to be thrown away and read for the next command. To solve this, I let the return type of the `Executable` interface be a enum called `ExitStatus`:

```java
public enum ExitStatus {
    finishCurrentIteration,
    terminate,
    continueExecute;
}
```

- `finishCurrentIteration`: any command after this in this iteration of the event loop shall be skipped;
- `terminate`: the whole application shall be terminated;
- `continueExecute`: the event loop can continue to running executables using the same tokens.

Hence, with all that, the code for execute in the `NestableExecutableObject` is as follows:

```java
class NestableExecutableObject implements Executable {
    // ...
    // this is abstracted out to avoid code duplication to run the 
    // preExecutables list and the postExecutable list
    private ExitStatus runExecutablesList(
        List<Executable> executables, String[] tokens
    ) {
        ExitStatus status = ExitStatus.continueExecute;
        for (Executable executable: executables) {
        status = executable.execute(tokens);
            if (status != ExitStatus.continueExecute) {
                return status;
            }
        }
        return status;
    }
	
    // the execute status
    @Override
    public ExitStatus execute(String[] tokens) {
        ExitStatus status = runExecutablesList(preExecutables, tokens);
        if (status != ExitStatus.continueExecute) {
            return status;
        }
        if (!identifiedExecutables.isEmpty()) {
            final Executable executable = identifiedExecutables.get(tokens[0]);
            if (executable != null) {
                // TokenUtilities is a helper class that I wrote to avoid code 
                // duplication.
                final String[] newTokens = TokenUtilities.instance.removeFirst(tokens);
                status = executable.execute(tokens);
                if (status != ExitStatus.continueExecute) {
                    return status;
                }
            }
        }
        return runExecutablesList(postExecutables, tokens);
    }
    // ...
}
```

## EventLoop

At this point, I’ve mentioned the event loop several times. The event loop shall be in charge of looping through and execute the root node (which is an executable), and terminate whenever the root node returns `ExitStatus.terminate` enum.

Hence:

```java
public abstract class EventLoop {
    // ...
    private final Executable rootExecutable;
    public abstract String[] getTokens();
    public void run() {
        ExitStatus status = ExitStatus.continueExecute;
        while (true) {
            status = rootExecutable.execute(getTokens());
            if (status == ExitStatus.terminate) {
                break;
            }
        }
    }
}
```

And I wrote a concrete class, DukeEventLoop, extending this class which gives a concrete implementation of `getTokens()`. The `getTokens()` reads from java’s `Scanner` and splits up the line into an array of tokens. 

## Simple Applications:

Now it would be very simple for us to implement some features like echoing: 

```java
public class Echo implements Executable {
    @Override
    public ExitStatus execute(String[] tokens) {
        System.out.println(String.join(" ", tokens));
        // after this, we would want it to skip the current execution loop.
        return ExitStatus.finishCurrentIteration;
    }
}
```

To add this feature:

```java
final Executable root = new NestableExecutableObject();

final Executable echo = new Echo();
root.registerPostExecutable(echo);

final EventLoop eventLoop = new DukeEventLoop();
eventLoop.run();
```

With this approach, we could also very easily make `Echo` an `IdentifiableExecutable`, i.e. only to execute if, say, the keyword contains echo.

```java
public class Echo implements IdentifiableExecutable {
    @Override 
    public String getId() {
        return "echo";
    }

    @Override
    public ExitStatus execute(String[] tokens) {
        System.out.println(String.join(" ", tokens));
        // after this, we would want it to skip the current execution loop.
        return ExitStatus.finishCurrentIteration;
    }
}
```

```java
final Executable echo = new Echo();
root.registerIdentifiedExecutable(echo);
// > echo hello
// hello
```

Of course, if we were to register echo to the `postExecutables` list, it would still behave the very same as before. 

# Stateful Commands

One thing that is common with the Echo and perhaps, Bye, is that **they do not have states**. The same `Executable`, when being executed 1000 times, would give you the same result for the 1000 times. This is not true however, when you are managing the tasks. 

## TaskManager

When you are managing tasks, you need to have states (i.e. the list of tasks). Furthermore, the state has to be shared among different Executables. If I were to create an Executable called delete and call it 10 times,  it should be able to delete the corresponding tasks from the same list of tasks. 

To do this, I created a class called `TaskManager` to maintain the state as a List of Tasks. 

```java
public class TaskManager {
    private List<Task> tasks;
}
```

And to create the Executable that helps manage the different state transitions, I used anonymous classes. For example, if I were to add a task to the task manager:

### Anonymous Classes

```java
public class TaskManager {
    // ...
    public IdentifiableExecutable getAddTaskExecutable() {
        return new IdentifiableExecutable() {
            @Override
            public String getId() {
                return "add";
            }
            @Override
            public ExitStatus execute(String[] tokens) {
                final Task task = Task.fromTokens(tokens);
                addTask(task);
                System.out.println("added: " + task);
                return ExitStatus.finishCurrentIteration;
            }
        };
    }
	// ...
}
```

And to use it:

```java
final TaskManager manager = new TaskManager();
root.registerIdentifiedExecutable(manager.getAddTaskExecutable());
```

With this approach, you would only need to create an anonymous class for each of usecase that you have, i.e. list the tasks, adding the tasks, etc. 

# ExecutableRegisterable

There is one last issue that I wish to fix, and that is about registering the `Executable`s with the classes. For some very simple stateless `Executable`’s, it would be just a one liner:

```java
root.registerIdentifiedExecutable(new Echo());
```

However, this would not be the same case with something as complicated as a `TaskManager`:

```java
final TaskManager manager = new TaskManager();
root.registerIdentifiedExecutable(manager.getAddTaskExecutable());
root.registerIdentifiedExecutable(manager.getDeleteTaskExecutable());
// ...
```

If you have say 10 functions, then you will have to do this for 10 times. Furthermore, it would be easy for you to get it wrong, say registering an `IdentifiedExecutable` as a post executable, which will always get executed if no match was found in the hashmap. Essentially, I think this is bad because **this requires you to know the internal workings** of the TaskManager class. In a way, requiring users to do this violates the “show not tell” rule from CS2030S. So, I created the `ExecutableRegisterable` interface:

```java
public interface ExecutableRegisterable {
    void register(NestableExecutableObject nestable);
}
```

implemented it in the `TaskManager`, marked all the getExecutable-alike functions in the `TaskManager` as **private**, and now, I would only have to do this:

```java
final ExecutableRegisterable manager = new TaskManager();
manager.register(root);
```

This way, regardless of how I mess with the code outside of the task manager, I would not make any mistakes as long as the register function works as expected — which should be a concern of the TaskManager but not anywhere else in the code.

**Comment by damithc** [comment]
Kudos for this detailed sharing @wxxedu Thanks for taking time to explain your approach.

**Comment by rmj1405** [comment]
Thank you so much for the detailed responses!! I'm glad to have learnt about different approaches to this task :)
