### ISSUE TITLE
How to handle issue creation for tasks with sub-tasks assigned to different members?

### ISSUE THREAD

**Issue by ChickenChiang** [nus-cs2103-AY2223S2/forum#232]
#### Say multiple members are creating a feature X in a project:
   - Person 1 is working on function A for feature X
   - Person 2 is working on function B for feature X
Should we create issue 'Implement feature X' and add sub-issues 'Implement function A for feature X' and 'implement function B for feature X' ? 

The example is as shown below:
![photo_2023-03-01_21-09-19](https://user-images.githubusercontent.com/96032660/222149320-bce37c77-5f50-4456-ad1c-1a17aa67b3d6.jpg)

**Comment by damithc** [comment]
@ChickenChiang the easiest solution is to create separate issues for each sub-task task, but also have a separate issue to track the overall progress of the main task -- i.e., same as what you have mentioned. 
Also keep in mind that we recommend dividing work by feature rather than dividing each feature among team members, to reduce dependencies between team members.
