### ISSUE TITLE
Help with smoke testing

### ISSUE THREAD

**Issue by fahim-tazz** [nus-cs2103-AY2223S2/forum#236]
Sorry for this last minute request, but could anyone smoke test my jar file on Linux and/or Windows?

You can unzip and run it with ```java -jar chad.jar```. 
[chad.jar.zip](https://github.com/nus-cs2103-AY2223S2/forum/files/10872051/chad.jar.zip)

**Comment by notle1706** [comment]
Hi @fahim-tazz, I am from your senior batch. I smoke-tested your product on Windows 10 and it works. This is a screenshot of your product. 
Edit: `bye` command works properly as well!
![image](https://user-images.githubusercontent.com/72089201/222675691-a9ac933e-e1a1-4ade-a166-c45530270a41.png)

**Comment by domlimm** [comment]
@fahim-tazz Hey fahim! I'm a senior from a previous batch dropping by to see if any of you need any help.

Have just smoke tested on Windows (both opening chad.jar and running the command you have provided), works perfectly! Love the images 🤣 

Here is the program when starting up:
![image](https://user-images.githubusercontent.com/46486515/222675258-6a16c6b1-c2ef-44f5-ae3e-c5700ca566fd.png)

Here is the text file that saves the tasks entered, after closing the application:
![image](https://user-images.githubusercontent.com/46486515/222675394-ca459ee0-152c-44f6-9612-6ac94b72c2c1.png)

Here is re-opening the program again:
![image](https://user-images.githubusercontent.com/46486515/222675693-aae47cbe-1aa8-4b87-af42-4f42930aec01.png)

**Comment by RussellDash332** [comment]
Hi @fahim-tazz, I'm a senior from the previous batch! Overall, your product works fine on my Windows 10 (both using command prompt and double-clicking the JAR file), i.e. no serious issue like crashing or errors. Good job! 😄 

<img src="https://user-images.githubusercontent.com/63991775/222677248-4472c570-7fdb-48c3-a1b6-9f2a1584a4c1.png" width="60%">

This is the image that I have after inserting several tasks and resizing the window. You can replace the `tasks.txt` file with the one I have:
```txt
T | 0 | 10293874382901-1
D | 0 | kill boss | 2020-10-10
T | 0 | save boss
E | 0 | save boss | 2020-10-10 | 2020-10-12
E | 0 | save boss | 2020-20-10 | 2020-10-12
E | 0 | save boss | 2020-2000-10 | 2020-10-12
T | 0 | hello
```

**Comment by QQH0828** [comment]
Hi @fahim-tazz, I'm your classmate at the same batch! Overall, your product works fine on my Windows 10 (both using command prompt and double-clicking the JAR file), Good job!

Here is the screenshot when I smoke-tested your product
![image](https://user-images.githubusercontent.com/122513302/222705291-8cd03259-23a0-4e19-8f27-89eedbfc0fe0.png)

Here is the text file after closing the application:
![image](https://user-images.githubusercontent.com/122513302/222705555-fa1b41b1-147b-490b-9bcc-62bf3055652a.png)

I have a few suggestions hopefully can help you improve your IP:

Firstly, maybe you can have one more command which is 'help', just simply show the command instructions, so the tester knows what can be tested and familiar with the command format such as datetime format. For example, I am not sure the datetime format at first, so I needed to try one time at least to know.  

Secondly, I noticed that the data will be saved only after the application closed. In order to not lost any data, maybe can save the data when there is a change instead of after the application closed.

Overall, I feel you did a good job with all functions work fine and your own personality! 😄

**Comment by Guanzhou03** [comment]
Hey, I'm from your senior batch and I did some basic testing on Windows. I've tested list, adding, marking tasks as well as the bye command and the functionality looks good, but it seems that I am also unable to resize the app to fit the window similar to what @RussellDash332 showed. Here is how it looked like on my end:
![image](https://user-images.githubusercontent.com/35629932/222727824-f9e338dd-0c8d-4b5d-a52c-4f73c4f4d8a1.png)

**Comment by fahim-tazz** [comment]
@notle1706 @RussellDash332 @Guanzhou03 @domlimm @QQH0828 Thank you all so much! Literally a life saver because I was running too close to the deadline.

Also thanks for the suggestions guys, I'll try and fix those issues.
