### ISSUE TITLE
Regarding Recommendation-CLI-First

### ISSUE THREAD

**Issue by praveenkrishna0512** [nus-cs2103-AY2223S2/forum#265]
My team is wondering if selecting GUI Regions in the app (ie. a mouse input to click) violates the recommendation to have the application be tailored to be CLI-First.

In essence, do the following examples violate the recommendations?
- If the user wants to view a contact in the AddressBook, but they have to scroll through a list to do so.
- If the user wants to select a contact in the AddressBook to view more details, but they have to click on the ListView object to do so.

Appreciate any help!

**Comment by damithc** [comment]
@praveenkrishna0512 If a CLI command can potentially be a faster way to get the same result (e.g., type `d 3` to see details of address at position 3), not providing such an option will make the app not 'optimized' for CLI users. 
Again, it also depends on the context. While we should try to design the UI in a way that users can avoid having to deal with long lists that require scrolling, in some cases that may be unavoidable.

**Comment by damithc** [comment]
@praveenkrishna0512 Also keep in mind that developer time and resources are limited. That means some features can be 'not in scope' for the current iteration, if there are other higher priority features that need to be implemented first. In such cases (i.e., features postponed to a future version because they were 'not in scope' for the current iteration), the team will not be penalized for not implementing them.

**Comment by praveenkrishna0512** [comment]
Alright thank you!
