### ISSUE TITLE
Red `DG Draft` task on tp progress dashboard despite updating DG b4 lecture

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#280]
My `DG Draft` task in my tp progress dashboard is red:

![image](https://user-images.githubusercontent.com/35413456/227763386-a18a6ac4-a31c-4855-b3fa-413dfc7af6af.png)

Despite add lines in our DG at commit https://github.com/AY2223S2-CS2103T-W12-2/tp/commit/882389b3788fb8d42755a2b1de2255aae9392f9e, which was done at `Mar 24, 2023, 1:39 PM`, before the 2pm Friday lecture.

Since there's no specified deadline the DG updating task *(as shown below)*, I assume the harddeadline was Mar 24, 2pm right?

![image](https://user-images.githubusercontent.com/35413456/227763533-19a57cd5-1e48-4634-8c78-e913fdc3ace4.png)

**Comment by damithc** [comment]
> Since there's no specified deadline the DG updating task _(as shown below)_, I assume the harddeadline was Mar 24, 2pm right?

@EvitanRelta Yes, that's correct.


> Despite add lines in our DG at commit [AY2223S2-CS2103T-W12-2/tp@882389b](https://github.com/AY2223S2-CS2103T-W12-2/tp/commit/882389b3788fb8d42755a2b1de2255aae9392f9e), which was done at `Mar 24, 2023, 1:39 PM`, before the 2pm Friday lecture.

@EvitanRelta Was this commit already merged to the master branch by the deadline? Only commits in the master branch are checked by our scripts.

**Comment by EvitanRelta** [comment]
> @EvitanRelta Was this commit already merged to the master branch by the deadline? Only commits in the master branch are checked by our scripts.

@damithc Yup! Here's the Git graph of our tp's repo _(ie. upstream remote not my fork)_. The DG-update commit and merge commit are highlighted:

![image](https://user-images.githubusercontent.com/35413456/227776030-bc8d6e1f-3c17-425b-9e4d-dda364087e43.png)

**Comment by damithc** [comment]
@EvitanRelta It looks like the authorship of that part of the DG was later taken over by a different member of your team, in https://github.com/AY2223S2-CS2103T-W12-2/tp/commit/5a7a895a6f19842dd873d8283a5a2299482396be

See https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking on how to override the auto-detected authorship 

On a related note, the `DG Draft` deliverable in week 10 is meant to get you familiarized with updating the 'Design' section of the DG, and PlantUML in particular -- so that you get an early estimation of how much effort that takes. The commit https://github.com/AY2223S2-CS2103T-W12-2/tp/commit/882389b3788fb8d42755a2b1de2255aae9392f9e doesn't match the spirit of that intention, although the dashboard script doesn't check for that specifically.

**Comment by EvitanRelta** [comment]
> See https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking on how to override the auto-detected authorship

But will adding `@@author` tags after the deadline allow the time sensitive `DG Draft` tag to detect it though?

**Comment by damithc** [comment]
> But will adding `@@author` tags after the deadline allow the time sensitive `DG Draft` tag to detect it though?

@EvitanRelta Yes, it should be able to detect it. If not detected 24 hours after the updated code is merged, let me know so that I can look into.

**Comment by damithc** [comment]
@EvitanRelta Also, it's not so important to turn this one item to green. A few red items should not affect your tP marks, unless you have many red items (i.e., less than 60% green items). The dashboard is mainly for you to track your own progress.
