### ISSUE TITLE
Issue With Duke Automated Testing

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#29]
Hi there,

I have started on setting up the automated testing for Duke and it seems to be working funny.

When i enter my commands manually, they work just fine and produce the intended output.
![image](https://user-images.githubusercontent.com/92144641/213445536-5e8b446a-4d49-457e-bd6f-cacd7e966b82.png)

but when i try to use runtest.bat on the same commands, it gives a NoSuchElementException.
![image](https://user-images.githubusercontent.com/92144641/213445634-d0666bfa-3777-4378-ab96-931fb69e0ed4.png)

what seems to be going wrong, here?

**Comment by EvitanRelta** [comment]
Try:
1. remove the last empty line (line 3 in ur pic) from input.txt
2. try manually entering nothing (and press enter) to see if it breaks

my guess is that ur code has no handling for empty commands. and that last empty line is an empty command that breaks the code.

**Comment by hingen** [comment]
Perhaps add a `bye` as the last line of your `input.txt`. I suspect what might have happened is that your entire `input.txt` has been read but since your program is still running, it attempts to read the next token which doesn't exist

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213448410-beb3726d-a0cc-4385-8ac2-bcff4f2bb234.png)

seems that neither are it?

for context, i left my file still as Duke.java, i didnt put it in a package, nor did i change anything in the runtest.bat file.

**Comment by EvitanRelta** [comment]
whats the line that causes this error?
as well as the surrounding lines of code for context.
im assuming its a `scanner.next()`?

**Comment by hingen** [comment]
Looked through your code and found the issue, this is the same as issue #28. Create Scanner object outside the while loop, do not create it multiple times. Refer to #28 for more info.

**Comment by Tempura-Person** [comment]
Oh, so that's what it was.
Funny OS thing, thanks!

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213455750-51c06686-5423-497b-b6b3-657596017e20.png)
huh, strange.
it seems to only read up to 'delete 2', it doesnt even print out my 'bye' message before terminating itself?

**Comment by WillCWX** [comment]
I have also looked through your code and the issue seems to be in `case "bye":` , specifically the `UserScanner.nextLine().length()` and how it interacts with your `input.txt`. (it reads up to `list` and has an issue with `bye` btw)

If you took a look at the top of the test, you would see a `java.util.NoSuchElementException: No line found` exception. This is because your `UserScanner.nextLine().length()` caused Duke to look for the next line but there were no next lines in your input.

Normally this would not be an issue as our own inputs have a newline character, `\n` that will not be picked up by `.next()` but will be picked up by `.nextLine()` for `.nextLine()` to terminate. 
> Input: `bye\n`
> `.next()` produces `"bye"` stopping at `\n`
>`.nextLine()` continues at `\n` and terminates as it sees the newline character, producing `""`

However, when you take a look at `input.txt`, you will see that your last command `bye` is the last line and hence, does not have a `\n` newline character! This causes the automated testing to fail even though typing your own `bye` command would still succeed.  

> Input: `bye`
> `.next()` produces `"bye"` stopping
>`.nextLine()` continues and is unable to terminate as does not see a newline character. 
> This reaches the EOF and causes an error

(windows uses \r\n as a line separator which .nextLine() also detects but the point still stands)

**Comment by Tempura-Person** [comment]
Thanks, I removed the error case entirely for the moment, now it works.
