### ISSUE TITLE
[iP] Level-7 file pathing

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#31]
Any good idea on how to store Duke data file into `[project_root]/data/duke.txt` properly? 

There will be a few differences in running the project either via runtest.sh and running from bash. 
The working directory will either be in `[project_root]/text-ui-test` or `[project_root]/src..../`

What is the best practice of getting a constant working directory, so that the data file can be saved in `[project_root]/data/duke.txt`.

**Comment by muhammadreyaaz** [comment]
I am not a TA but what I did was to check the current working directory and then append a fixed file path if the working directory is different from /data. I am not sure if this is the correct approach, but it seems to be working for me if I run from different folders.

**Comment by hingen** [comment]
Was thinking perhaps start from the current working directory then slowly traverse the parents looking for a directory which contains a directory named `src` since we know for a fact that the project root folder has a directory named `src`.

```java
Path path = Path.of(System.getProperty("user.dir")); // Get the path to the current working directory

while (true) {
    File dir = path.toFile();

    boolean isFound = false;
    for (File file : dir.listFiles()) {
        if (file.getName().equals("src")) { // Check if this directory contains a file/directory named 'src'
            isFound = true;
            break;
        }
    }

    if (isFound) {
        break;
    }

    path = path.getParent(); // Move to the next parent
}

Path savePath = Paths.get(path.toString(), "data", "duke.txt");

System.out.println(savePath);
```

But the solution isn't perfect as it might fail if the current working directory is an ancestor of the project root directory or if you have multiple files/directories named `src` in your project.

An alternative solution would be to perhaps save to the user's home directory which can be obtained using `System.getProperty("home.dir")`. I know some standalone Linux apps do this. Not sure what is the convention for Windows and Mac.

**Comment by damithc** [comment]
> since we know for a fact that the project root folder has a directory named `src`.

@hingen Only the developers will have such a folder. Users of the product will not have such a folder.

**Comment by hingen** [comment]
> Only the developers will have such a folder. Users of the product will not have such a folder.

Ah I see, my bad, I did not take into account that the users may not have the `src` folder since it's not necessary for deployment.

If we're discussing deployment scenarios, then, perhaps write to a file in `System.getProperty("home.dir")`. Since it is the user's home directory, it should be a directory that the user has write access to (or at least for most users). It also has the benefit that the app will run fine even if the user runs the app from a working directory which he/she does not have write access to (example `/`).

**Comment by daitenshionyan** [comment]
I was thinking of creating a file utility class containing this static method that is used to create the save directory. It returns `true` only if the directory exists when it returns.

```java
public static boolean mkdirs(Path path) {
    if (path.toFile().exists()) {
        return true;
    }
    return path.toFile().mkdirs();
}
```

So reading and writing will be something like this:

```java
String dirPathString = "save_data";
String filePathString = "/test.txt";
String content = "abcd";
try {
    if (!FileUtils.mkdirs(Paths.get(dirPathString))) {
        throw new IOException("Failed to create file");
    }
    // method to write file
    FileUtils.writeFile(Paths.get(dirPathString, filePathString), content);
    // method to read file
    System.out.println(FileUtils.readFile(Paths.get(dirPathString, filePathString)));
} catch (IOException ioEx) {
    ioEx.printStackTrace();
}
```
The directory path here is relative to where the program is running and there is no need to find the root directory. This works for me but I also do not know if this is the best approach and would like to get some feedback.

**Comment by ExtraShotLatte** [comment]
Hello @daitenshionyan and OP!

I have a similar approach to daitenshionyan. I implemented this using the package from `org.apache.commons.io.FileUtils` which it's documentation can be found [here](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/index.html?org/apache/commons/io/FileUtils.html#:~:text=Makes%20a%20directory%2C%20including%20any%20necessary%20but%20nonexistent%20parent%20directories.).

I tried to use the `write` method in the package. Writing to the file inside `~/data/test.txt` (the data directory was not created prior) cause the directory `data` to be created as well (to my pleasant surprise). Am not sure if there is a benefit to creating the directory first before using `FileUtils` to create the file directly. In my own testing, `FileUtils` did not touch the original files that was already present in the directory.

However, I noted that [this requirement about Cross-Platform File Paths in Java](https://www.sghill.net/2014/how-do-i-make-cross-platform-file-paths-in-java/) may come in handy for inter-platform compatibility of the software we are writing, since both Windows and other OS uses a different way to handle and specify directory.
![image](https://user-images.githubusercontent.com/58366602/214108985-3e10da69-5eb3-4ac9-827b-df0586c76803.png)


```java
String home = System.getProperty("user.home");
java.nio.file.Path path;
File newFile;

path = java.nio.file.Paths.get(home, "data", s);
newFile = new File(path.toString());
FileUtils.write(newFile, "Test\ning");
```

seems to create the test file just fine without any issues, it even adds the `data` parent directory for me! :D

**Comment by lhy-hoyin** [comment]
I have a similar method too, which creates and writes to directories/files that are relative to where the `JAR` file is.
Another point I like about it is that I don't have to worry if the directory exists, Since it also create them for me.

```java
private void writeToFile(String filePath, String fileContent) {
    try {
        Path f = Paths.get(filePath);
        Files.createDirectories(f.getParent()); // Create directory (if not exist)
        if (!Files.exists(f)) {
            Files.createFile(f); // Create non-existing file
        }
        Files.writeString(f, fileContent); // Write to file
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

**Comment by Hikoya** [comment]
Hi @francisyzy , I am a senior from the previous batch. Please close this issue if there are no more confusion :)
