### ISSUE TITLE
Making minor Ui change to fix a bug

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#317]
We have a command `remark INDEX` which opens a popup for user to edit the "remark" field of the `Person`.  
However, while the popup is open, the user can still type commands, which can cause unexpected behaviour, as shown below:

![able to enter command while popup](https://user-images.githubusercontent.com/35413456/229692673-a2a9b97e-5722-438d-bca9-8c7156e63518.gif)

While this is clearly a **<ins>bug</ins>** _(not a flaw)_, the fix we're planning is to disable the command line inputbox while the popup is open _(which is a Ui change)_. 

Is it allowed?

**Comment by damithc** [comment]
@EvitanRelta Looks like the feature design currently does not block certain user behaviors that can cause problems. If the user behaves as intended, everything is fine. Based on the strict definition of bugs that we use for the feature freeze, this is not a bug but a design flaw. Examples of bugs in this context: the pop up not showing up when it should, the content of the edited remark not being saved as intended. 

Hence, you can update the UG to warn users not to edit the command while performing this particular task. You can also include it as a planned enhancement so that you will not be penalized for it in the PE.
