### ISSUE TITLE
Question regarding AB3 authorship when it comes to refactoring

### ISSUE THREAD

**Issue by lywich** [nus-cs2103-AY2223S2/forum#355]
In the context of code reuse, how do we handle refactored code from the original AB3 being attributed to a member because they refactored a file. For example, "person" from AB3 (and all reference to "person") was changed to something else. Will this be a problem when it comes to code reuse as the module website said not to take credit for existing AB3 code unless significant modification was made?

**Comment by damithc** [comment]
@lywich RepoSense will automatically attribute such code to the person who refactored it. But if you want to 'disown' that code because the refactoring was not significant enough, you can use empty `@@author` tags, as given [here](https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking:~:text=Adding%20%40%40author%20tags%20to%20indicate%20authorship).
