### ISSUE TITLE
Bugs for UG / DG page breaks

### ISSUE THREAD

**Issue by Infrix** [nus-cs2103-AY2223S2/forum#382]
There is a bunch of bugs mentioning UG and DG page break.

![image](https://user-images.githubusercontent.com/88615976/232273866-cbd6c775-9ed9-44ff-a151-a57c85b52111.png)
For instance, a bug report stating that our component section was disrupted by a page break.

![image](https://user-images.githubusercontent.com/88615976/232274330-dce416ee-d130-4e67-9ed7-b973dec227f1.png)
In another instance, a similar bug report stating that another section was disrupted by a page break.

We received around 5 of these bugs at different sections of our UG/DG.  
I understand that this could be a little disruptive for readers, but in some cases it is quite unavoidable. 
Should these be accepted as a documentation bug or should they be considered notInScope?

If it is, should we be accepting all of them or just one of them?

**Comment by damithc** [comment]
@Infrix page breaks appearing in the middle of a paragraph is common and readers should be used to it already e.g.,

![image](https://user-images.githubusercontent.com/1673303/232276535-5a4dfb64-da4e-4ee9-aaa0-75c6b3a40aac.png)

But a page break in the middle of some type of content (e.g., in the middle of a detailed diagram) can hinder the reader and should be avoided.

>I understand that this could be a little disruptive for readers, but in some cases it is quite unavoidable.
Should these be accepted as a documentation bug or should they be considered notInScope?

You can factor in my general comment above when deciding. Other are welcome to chime in with their opinions. 

> If it is, should we be accepting all of them or just one of them?

If you want to combine them, email me the exact number of distinct cases (i.e., ignoring the report of exact same case) you want to combine so that I can advise you on how to upgrade the severity to match.
