### ISSUE TITLE
Regarding Weekly Quiz Score

### ISSUE THREAD

**Issue by MrTwit99** [nus-cs2103-AY2223S2/forum#39]
Hi Prof, I noticed the option for us to view our Weekly Quiz score has been disabled.

Would it be possible for you to enable it once again? This would allow us to know if we have met the minimum requirement of 70% correct and reattempt should we not hit the requirement.

**Comment by damithc** [comment]
@MrTwit99 the score was shown in the first few quizzes due to a misconfiguration. 'Redo until 70%' is not the intention of the quiz. The intention is that you read the topics well and make one sincere attempt at the quiz. The multiple attempts option is there to cater for accidental submissions. As the questions are not that difficult (they are there mostly to verify you've read the topic, not to test a deeper understanding because such a deeper understanding cannot be expected soon after reading a topic), and there are bonus questions as well, it is almost impossible to fall below 70% if do the quiz as intended. For good measure, you can do the quiz before Monday so that you earn an extra point as well.
