### ISSUE TITLE
Precedence of Bug Type

### ISSUE THREAD

**Issue by Beebeeoii** [nus-cs2103-AY2223S2/forum#390]
If there is a bug that differs from the UG (for example, UG advertises that the app can do A, but the app does B instead), is it more right to say that it is a documentation bug as the UG is not updated to reflect that the app does B now, or is it more right to say that it is a feature flaw since there is a difference between the UG and the app?

thanks !

**Comment by damithc** [comment]
@Beebeeoii Provided both options (i.e., changing the app or the UG) are viable, this is largely the team's call. 

If you are worried that this will affect your accuracy bonus, not to worry; we already take this into account when calculating the accuracy.

**Comment by Beebeeoii** [comment]
thanks !

**Comment by damithc** [comment]
@Beebeeoii To add, if both `type.FeatureFlaw` and `type.DocumentationBug` are viable categories for a bug, if the bug was reported during Phase 1 Part II (during which only the latter category is allowed), the team should not reject it for being a feature flaw that was reported during the documentation testing period.
