### ISSUE TITLE
Level 7 and Level 8 Parallel Branching

### ISSUE THREAD

**Issue by anunayajoshi** [nus-cs2103-AY2223S2/forum#40]
Hello, So I am working on Level 7 and Level 8 of the IP. And we are told to work on them on parallel, and only merge after both are done. I have completed Level 7, and changed to a new branch for Level-8, but the code still remains the same. Are we supposed to git add , and commit the code within level 7 first, and then change the branch, or is the code meant to be unchanged when changing the branch. If the code doesn't change, the benefits of branching doesn't really make sense to me.

**Comment by mmaimer33** [comment]
> Are we supposed to git add , and commit the code within level 7 first, and then change the branch, or is the code meant to be unchanged when changing the branch.

From the assignment it looks like we have to merge the branches only after both their implementation is complete, so the starting code would remain the same when working on either. Committing the code to each branch without merging would be wise, but would not affect other branches.

I think this requirement exists to help us appreciate how branches can be used. Level-7 and level-8 are unrelated and can use the same base code to build on. Because of this, in theory, there could be two people different people working on each aspect at the same time, and branches enable this by giving each a separate copy of the code to prevent interference. Any conflict resolution only needs to happen during merging that way.

**Comment by damithc** [comment]
> Are we supposed to git add , and commit the code within level 7 first, and then change the branch,

@anunayajoshi Yes, level 7 work should be committed to its own branch before you start a branch for level 8. If the code is not committed first, those changes will be visible to you when doing level 8, which, as you realized, doesn't give you the benefits of branching.

**Comment by anunayajoshi** [comment]
Thank you for the clarification @damithc !
