### ISSUE TITLE
What is a boundary in BVA?

### ISSUE THREAD

**Issue by hingen** [nus-cs2103-AY2223S2/forum#400]
In BVA, do the boundaries refer to boundaries between partitions or the boundaries of each partition?

Suppose I have the EPs: [1-3] [4-6] [7-9]
Are 1 and 9 considered boundaries in BVA?

**Comment by pangrwa** [comment]
Based on my understanding, I think that the boundaries refer to each partition. So maybe we have to consider 1,34,6 and 7,9. But I'm not too sure.

**Comment by hingen** [comment]
@pangrwa Thanks for giving your thoughts. That's my initial thought as well.

What got me confused is that it is mentioned [here](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/testCaseDesign.html#boundary-value-analysis) that:

> This is not surprising, as the end points of boundaries are often used in **branching instructions**, etc., where the programmer can make mistakes

If the reason for BVA existing is because of branching, would it only apply to boundaries between partitions?

**Comment by damithc** [comment]
> Based on my understanding, I think that the boundaries refer to each partition. So maybe we have to consider 1,34,6 and 7,9. But I'm not too sure.

@pangrwa this is correct.

> If the reason for BVA existing is because of branching, would it only apply to boundaries between partitions?

@hingen Based on the definition of equivalence partitions, the SUT's execution for inputs of a partition is likely to be similar, but it also implies that the execution for the adjacent inputs are different (otherwise we can simply make the partition larger to capture those inputs too). Hence, a execution behavior change is likely to occur near the boundaries of the partition,  which means each boundary of each partition can potentially be involved in a branching instruction.

**Comment by hingen** [comment]
I see, thanks prof!
