### ISSUE TITLE
difference between NFR and multiplicity

### ISSUE THREAD

**Issue by alextang809** [nus-cs2103-AY2223S2/forum#407]
<img width="680" alt="Screenshot 2023-04-24 at 3 50 11 PM" src="https://user-images.githubusercontent.com/62707493/233933080-d18d9066-8b31-4515-8162-dba6f4d49f2f.png">
can "A course should be able to have up to 2000 students" also be interpreted as FR because of 0..2000 can also be treated as multiplicity?

**Comment by gremmyz** [comment]
I think this is a good question and would like to hear others' views on it.

IMO, yes, I think it could also be intepreted as a FR since it's specifying what the system should do (hold up to 2000 students). Maybe a better way to make it clear that it's a NFR would be to specify that "a course should be able to have up to 2000 students without noticable lag" or something regarding the performance aspect?

**Comment by damithc** [comment]
Good question @alextang809 

In some cases requirements can be in the grey area of FR and NFR. And as we always say, the correct categorization doesn't matter as much as fulfilling the requirement appropriately.

In this case, 'a course being able to contain students' is the functional part of the requirement (which we assume is implied or stated elsewhere), and the upper limit of the course size is a performance requirement (which is closer to NFRs). But yes, we can also argue that the max class size is part of the FR. The more important thing (in a real project) is to ask questions such as  "how many students a typical course can have?", "what's the maximum possible class size?" etc. which we often forget to do.

BTW, an NFR can be give rise to a multiplicity being defined; there is no rule against that.

**Comment by alextang809** [comment]
thanks prof! question resolved clearly now!
