### ISSUE TITLE
Why no backward navigation during exam

### ISSUE THREAD

**Issue by jiasheng59** [nus-cs2103-AY2223S2/forum#414]
Why is the format not allowing navigate back to previous question? It's claimed that (i) this is more aligned with real life project discussion scenario, (ii) test your proficiency and (iii) avoid over the shoulder attack. Moreover, prof claimed that this format wouldn't make the exam harder.

I would argue that this is not true. (i) if you make a mistake/misinterpret something during discussion, and you realize the mistake before the it's too late, you should indeed **reflect** on what you said and **correct** it, not just run away from your mistake just because the meeting has passed. (ii) If one is able to correct his/her mistake within limited time constraint, isn't this showing his/her proficiency? Does "not able to answer a question within short timespan" imply the person is not proficient in that topic? (iii) If one were to conduct over the shoulder attack, even copying one single question should be considered cheating. The seat allocation is not chosen by students and not under students' control, how can this be used as a reason to affect the exam format... (I would rather be placed in a room with only one student and be invigilated by an invigilator, than to take a non-navigation exam)

In fact, the truth is not everyone masters every concept equally well. Some may be more knowledgeable in certain aspect of topics being covered and this may save his some on answering certain type questions. This extra time saved can sometime be helpful for him to interpret those questions that he's unfamiliar with more deeply. 

I know this won't affect the upcoming exam format anyway. I'm just here to express my disagreement. (No offense 😄)

-Jia Sheng

**Comment by jiasheng59** [comment]
Well, I recall one of the takeaways from this module is to 
>"Learn to follow"

So I guess there's no point to argue this~

(but still, it's to express my disapproval, disagreement and dislike towards any non backward navigable exam)

**Comment by damithc** [comment]
@jiasheng59 Sorry, I meant to reply earlier but slipped my mind due to exam work. Your negative feelings about the issue in concern have been well-noted, but as you noted, we are not able to change anything about the exam of this semester.

Yes it is not ideal to block backward navigation in exams (there are pros and cons).

Yes, sometimes one can be incorrect in the first try (in the exam, but also in a real life project discussion) but can figure it out soon enough, which is better than not figuring it out at all. Nevertheless, we should aim to not to have to do that too often; it is not good if you are noticed as the one who 'self-correct'  more often than others during a project meeting.

So, ideally, we should be able to differentiate between these three:
1. Those who gets the correct answer in the first try
2. Those who answer incorrectly at first, but are able to self-rectify within a short time
3. Those who answer incorrectly but doesn't realize it even later

Blocking backward navigation allows us to differentiate between 1 and 2 but it lumps 2 and 3 together. Allowing backward navigation lumps 1 and 2 together, but differentiates between 2 and 3. So, neither is ideal, and there are other pros/cons as well. That said, the module grade has many components, evaluating students in many different ways, some of which actively promote self-correcting. 

Yes, not knowing who sits in front does reduce some forms of copying but it still opens the door for other types of planned and ad hoc cheating/collusion. To give an example, if one has very low confidence in their own answers, being able to see the answers of two other 'random' students can help to make the final choice. I will not elaborate here on other more serious possibilities of cheating it can lead to. We want to be 'safe than sorry' on this front, as even one such case can potentially tarnish the reputation of the school.
