### ISSUE TITLE
Week 8's Tutorial (Class Diagram)

### ISSUE THREAD

**Issue by venuslimm** [nus-cs2103-AY2223S2/forum#421]
Hello, may I know why there isn't a composition between `StockItem -> Review`? 

`StockItem` consists of `Review`. Also, `Review` cannot exist without `StockItem`, similar to how `Rating` cannot exist without `Review`.

Code:
![image](https://user-images.githubusercontent.com/50315976/234211996-4a5a7408-3514-4951-b6ea-a61e455428b2.png)

Answer given:
![image](https://user-images.githubusercontent.com/50315976/234211660-8e2ed158-96fd-4e88-aacc-a835e4574e02.png)

**Comment by damithc** [comment]
@venuslimm delete cascading is a side effect of composition, not a sufficient condition for it.

![image](https://user-images.githubusercontent.com/1673303/234240153-4dc4123d-e8b3-4dc8-89b8-2a60e3c7a3e6.png)

Yes, a review cannot exist without a corresponding stock item, but conceptually, is a review _part of_ a stock item? The answer may be subjective but it feels like reviews are entities in their own rights that get attached to stock items rather than being part of a stock item. Still, the decision for deciding if an association is actually a composition is not very clear cut.

**Comment by venuslimm** [comment]
Okay, thank you!
