### ISSUE TITLE
Object Diagram to Class Diagram

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#427]
![image](https://user-images.githubusercontent.com/108938188/234227740-f135148d-e96f-4534-860b-a5008594c9d8.png)

Why is the last option not correct?

**Comment by inas0ng** [comment]
I think it's because the last class diagram option states that every Table object should be associated with exactly 1 Door object, which is not the case in the given object diagram.

Edit: Realised this has been answered previously, see [here](https://github.com/nus-cs2103-AY2223S2/forum/issues/410)

**Comment by damithc** [comment]
@FredericChow00 Your screenshot looks like an old version of the practice exam answers. It might not match the one you did in Examplify.

**Comment by FredericChow00** [comment]
Got it thanks so much for the help!
