### ISSUE TITLE
tp dashboard not showing attributes

### ISSUE THREAD

**Issue by jinnieshin** [nus-cs2103-AY2223S2/forum#437]
Hi prof, I have done [v1.1 PRs](https://github.com/AY2223S2-CS2103T-T12-1/tp/pull/55), [v1.2 PRs](https://github.com/AY2223S2-CS2103T-T12-1/tp/pull/75) and [PPP Draft](https://github.com/AY2223S2-CS2103T-T12-1/tp/pull/196) but was not captured on the dashboard. I would appreciate if the commitment is considered.

**Comment by damithc** [comment]
@jinnieshin  
PRs need to follow the forking workflow to be counted. The ones you have cited come from the master branch of your fork, which means they don't follow the for forking workflow fully.
PPP Draft is a time-sensitive deliverable, which means it needs to be done within the week it appears. I did not check this but I suspect that is why it doesn't appear in the dashboard.  If not, let me know so that I can look into it further.

**Comment by jinnieshin** [comment]
Oh I see, may I ask whether there would be anything I can do to include it into the dashboard? Should I add equivalent tags in the fork?

**Comment by damithc** [comment]
> Oh I see, may I ask whether there would be anything I can do to include it into the dashboard? Should I add equivalent tags in the fork?

Not at this time. But having a few red items in the dashboard shouldn't affect marks, unless you have many red items.

**Comment by jinnieshin** [comment]
Okay. Thank you for answering!
