### ISSUE TITLE
runtest.bat: FC is not a recognised command

### ISSUE THREAD

**Issue by euph00** [nus-cs2103-AY2223S2/forum#44]
I have attempted to run runtest.bat by `./runtest.bat` from my command line (powershell, windows 11) while in the directory text-ui-test and it works fine until the last line where file compare is invoked. It seems to insist that 
`FC is not recognised as in internal or external command, operable program or batch file`
which got me a bit confused. It is not much of an issue as I am able to work around it and the runtest.sh bash script works for me no issues. Just curious how I would fix this issue or what I am doing wrong.

**Comment by RichDom2185** [comment]
Hi @euph00, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Can you check if you are able to run `./runtest.bat` using the normal Command Prompt instead of PowerShell? The `.bat` file extension suggests that it is a batch file, which is supposed to be run in command prompt.

**Comment by euph00** [comment]
@RichDom2185 thanks for the suggestion, that works properly now. I was under the impression that ps and cmd were functionally identical except ps supports scripting in powershell as well. Thanks for the help and sorry for noob mistake
