### ISSUE TITLE
Junit Test

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#49]
Are the test cases supposed to be run on individual class methods? Or are we suppose to run Duke and feed it inputs, and compare actual output to the expected

**Comment by damithc** [comment]
@seadragon2000341 At this time you'll be using JUnit for unit testing. So, the former.

**Comment by anunayajoshi** [comment]
I think JUnit is able to simulate "running Duke and feeding the inputs as well", and does the work of comparing the output to expected. I can create "new Duke" within the test case itself and it can compare the outputs like when we used text-ui-test.

But it's better to test out the smaller components of Duke instead of Duke itself, as there are a lot of different parts working together and it'll make it easier to find where the fault is.
