### ISSUE TITLE
Why is auto-updating of pull request the default behaviour?

### ISSUE THREAD

**Issue by joellow88** [nus-cs2103-AY2223S2/forum#51]
I refer to the textbook paragraph 

> Textbook → Git & GitHub → Creating PRs 

> You can update the PR along the way too. Suppose PR reviewers suggested a certain improvement to your proposed code. To update your PR as per the suggestion, you can simply modify the code in your local repo, commit the updated code to the same master branch, and push to your fork as you did earlier. The PR will auto-update accordingly.

From what I understand, this means that after we create a pull request, any new changes we push to our fork will be automatically included in the pull request. 

To me, this seem undesirable as pull requests are created once we are relatively confident of our code and ready to merge it with the upstream repo. Meanwhile, pushing code into our fork affects only our own remote repo, so the code may still be in development and not ready yet.

By having a PR update automatically when pushing into our remote repo, we will not be able to push any more code into our own remote repo, unless we are also confident that it is ready to merge with the upstream repo. This defeats the point of having our own remote repo in the first place. 

Would appreciate some clarifications as to whether my understanding of this auto-updating behaviour is correct, and whether there is a way to disable it.

Thanks!

**Comment by damithc** [comment]
Kudos for noticing this problem right away @joellow88 There are remedies for this problem; let's wait for others to pitch in with what they think about this.

**Comment by ExtraShotLatte** [comment]
I also thought about the same thing! However, I think it makes sense because of the following (in my own opinion):

1.  Different features are supposed to be done in different branches. By creating a PR, typically you are contributing ready to be implemented feature to the upstream repo, hence, you can create multiple PR (based on different branches) if you do have multiple features' implementation you intend to contribute.
2. After creating a PR, you may have caught small mistakes that could be an oversight during your initial developer testing. By having new commits of the branch automatically updating to the latest version you have, you can fix these before the PR review takes place (and not send multiple PR request).
3. After creating a PR, a peer or senior developer may look through the code and can potentially give comments or suggestions to the code. By having the commits automatically be included in the PR, it seems a little neater as the PR reviewer can just look at newer commits and approve the PR based on the further contributions.

However, this also led me to think, should v1.1, v1.2, v1.3 (different iterations) of the same feature (but done at different point of time) be on the same branch if the branch automatically updates when you make new commits? I imagine a scenario where I want to work on v1.2 of the same project (same feature) after completing v1.1 but I cannot because I'm waiting for PR to be reviewed and approved :/

If I understood any of the concepts wrongly, but please feel free to correct me if I do! 

Cheers :)

**Comment by Zxun2** [comment]
@ExtraShotLatte These are definitely some valid points! It can make it easier to fix small mistakes and keep reviewers informed of progress without having to send multiple pull requests.

As for the question about different iterations of the same feature, I believe that two main ways that you can go about doing it. Some prefer to work on different iterations of a feature in different branches, while others prefer to work on different iterations in the same branch.

If you prefer to work on different iterations in different branches, you can create a new branch for each iteration, make your changes, and create a new pull request for each one. This can help keep the codebase organized and make it easier to review and merge each iteration separately.

If you prefer to work on different iterations in the same branch, you can do so by making use of the `git stash` command to temporarily store your changes, make it easy to switch between different feature's implementations or different versions of the same feature. In this case, it's also important to clearly label and document your different iterations and versions, such as by adding comments or commit messages that explain what changes were made in each iteration. 

Let me know if I miss out anything!
