### ISSUE TITLE
Special characters in Java

### ISSUE THREAD

**Issue by lyndonlim27** [nus-cs2103-AY2223S2/forum#52]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/80683209/214111133-1c7a234f-57c4-4cb4-8872-1b94c18f68df.png">

I have been trying to figure out why I had trouble splitting a string with "|" and found out I needed to \\ it. But why when I check if it contains "|" it works as intended?  So when do I need to \\ it.

Thanks!

**Comment by ExtraShotLatte** [comment]
Based on my understanding from [Java 11 API](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html), the method `contains` takes in `CharSequence` but the method `split` takes in a `String regex`.

I looked up [this](https://www.w3schools.com/java/java_regex.asp) and found out that the character `|` has a special meaning in regex:

Find a match for any one of the patterns separated by | as in: cat|dog|fish

I believe this is the main reason why you would need the `\\|` for the split method but not need it for the `contains` method, as one expects a char sequence and one expects a String regex!

Hope this helps! Do correct me if there I made a mistake :)

**Comment by Jnjy** [comment]
Thanks OP for the question!

Adding on to Sean’s answer, the java split() function takes in regex and | is the logical `OR` expression. In order to split word using the indicated character `|`, you would need to use the escape character `\`. However, since `\` is also a meta character in String literal, you would need another `\` to escape it. Hence, you would need `\\|` as mentioned by Sean. An alternative way to split is to use `split(Pattern.quote(‘|’))`. I have attached the function definition below for your reference.

![image](https://user-images.githubusercontent.com/87219903/214209662-c13762af-ed78-4e5b-b98b-0f16f8adfe4d.jpeg)

`Contains()` method simply searches char sequences in the given string and `|` is in the given string.

You may reference to the image below as which characters require the escape sequence.

![image](https://user-images.githubusercontent.com/87219903/214209968-4385850c-8ad8-4b7f-bdac-771c2bd39f05.jpeg)

**Comment by lyndonlim27** [comment]
Thank you so much!
