### ISSUE TITLE
Code reads date wrongly

### ISSUE THREAD

**Issue by thennant** [nus-cs2103-AY2223S2/forum#54]
![image](https://user-images.githubusercontent.com/97217532/214221317-a6060900-006e-4865-8c77-a14573a2052c.png)
![image](https://user-images.githubusercontent.com/97217532/214221934-8462d2a6-43a3-4f80-a234-7bda8225d9a1.png)

My code outputs the date correctly when the deadline date is given in the year/month/day format but for some reason, it still gives a date when the deadline date is given in the day/month/year format. Any ideas on how to get it to only recognize the year/month/day format only?

**Comment by damithc** [comment]
@thennant As we wait for answers from peers, note that [we recommend](https://nus-cs2103-ay2223s2.github.io/website/admin/appendixD-help.html) using [code blocks syntax](https://www.markdownguide.org/extended-syntax/#syntax-highlighting) rather than screenshots when posting code snippets. Reason: To make it easier for others to copy-paste-modify code when answering or trying to figure out the answer.

**Comment by hingen** [comment]
It would appear that what `SimpleDateFormat::parse(String)` is doing is that it reads `2/12/2019` as year=2, month=12, day=2019. Of course, December does not have 2019 days so month and year get incremented instead.

Here's some simple code to illustrate what is going on: 
```java
String input = "1/01/32";

DateFormat inFormat = new SimpleDateFormat("yyyy/MM/dd");
Date date = inFormat.parse(input);

DateFormat outFormat = new SimpleDateFormat("dd/MM/yyyy HHmm");
System.out.println(outFormat.format(date));

// Output is: 01/02/0001 0000
```
In this case, the date parsed is year=1, month=1, day=32. But January only has 31 days, so the resulting date becomes 1 Feb 0001. 

This is just speculation since I don't know how `Date` works exactly but perhaps `SimpleDateFormat::parse(String)` simply calculates the date as milliseconds since January 1, 1970 and stores it as a long, without doing any error checking for whether the day exceeds the number of days in the month.

If you would like something with stricter error checking, perhaps consider using the newer `DateTimeFormatter` class instead. Example below:
```java
String input1 = "1/01/32";
String input2 = "0001/01/32";
String input3 = "0001/02/01";

String format = "yyyy/MM/dd";
DateTimeFormatter formatter = DateTimeFormatter.ofPattern(format);

try {
    formatter.parse(input1);
} catch (DateTimeParseException e) {
    System.out.println("DateTimeParseException thrown");
}

try {
    formatter.parse(input2);
} catch (DateTimeParseException e) {
    System.out.println("DateTimeParseException thrown");
}

DateTimeFormatter outFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
System.out.println(outFormatter.format(formatter.parse(input3)));

// Output is:
// DateTimeParseException thrown
// DateTimeParseException thrown
// 01/02/0001
```

**Comment by thennant** [comment]
ok thank you!
