### ISSUE TITLE
No tasks in Gradle

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#60]
Hello everyone,

When I click on the elephant gradle button in Intellij, I can not see any tasks. Is this supposed to be the case?
![image](https://user-images.githubusercontent.com/78403168/214477874-962f133e-2d86-48f2-8a9c-dcddb943d155.png)

**Comment by hingen** [comment]
@seadragon2000341 
![image](https://user-images.githubusercontent.com/31367001/214478812-cecd165f-707a-47bb-8bc2-b2bd71709d44.png)

Did you miss out any steps from the [gradle tutorial](https://se-education.org/guides/tutorials/gradle.html)?

**Comment by seadragon2000341** [comment]
Ah yes, it works now. I just had to redo the whole thing. Thanks!

**Comment by seadragon2000341** [comment]
One more qns - whenever I run Duke and press stop, the following error message occurs. Is this supposed to be normal?
![image](https://user-images.githubusercontent.com/78403168/214481446-d1908b13-e91c-4254-a5db-38a520552701.png)

**Comment by hingen** [comment]
Should be fine. The error message is not from your duke code but from gradle. An `org.gradle.api.BuildCancelledException` was thrown by gradle because you forced the program to terminate. If you exit duke normally (e.g. using a `bye` command), you won't get the error.

If you want to see more information about the error, just click `Run with --stacktrace` in the error message, wait for duke to start, then press stop. You'll see the full error message outputted by gradle.
