### ISSUE TITLE
Wildcard Imports

### ISSUE THREAD

**Issue by wxxedu** [nus-cs2103-AY2223S2/forum#69]
In the first tutorial, we were shown some style violations. One of them is wildcard imports. However, my IDEA seems to always merge these imports to a wildcard import. I am wondering if it would be ok to just leave it as is, or should I just disable the auto-formatting of the IDE. Thanks!

**Comment by lhy-hoyin** [comment]
You should probably disable the auto-formatting. Otherwise, when the IDE does it for you, it becomes you that violate the coding standard stated out for this module. 

If you know how to, could you indicate which IDE you are using? And the steps to disable the auto-formatting?
I believe this would also help others that are facing the same issue as you.

**Comment by damithc** [comment]
If using Intellij IDEA, this may be useful https://se-education.org/guides/tutorials/intellijCodeStyle.html

**Comment by wxxedu** [comment]
Got it, thanks! I was using IDEA's auto formatting.
