### ISSUE TITLE
push command on CLI not working

### ISSUE THREAD

**Issue by tituswe** [nus-cs2103-AY2223S2/forum#7]
Under section W2.4e push: Uploading data to other repos, I followed the instructions as per activity.

Upon entering the command `git push origin master`, and entering my GitHub username and password, I am shown the following error message: 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/tituswe/samplerepo-things.git/'

Could someone explain why this is happening? Thank you.

**Comment by Junyi00** [comment]
I believe one of the recommended forms of authentication is through the use of **Personal Access Token**, which is described [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). It can be created [here](https://github.com/settings/tokens). 
However, u should look up instructions on storing the created credential on your local machine since it differs for different OSs.

**Comment by hingen** [comment]
As the message implies, seems like GitHub has removed password authentication. A post was made on their developer blog [here](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/) (although they seem to have officially removed it later than in the timeline specified)

The recommended replacement seems to be Personal Access Token. Personally, I prefer using SSH. You can refer to this guide [here](https://www.awordfromnet.com/how-to-connect-github-with-sourcetree/) on how to setup SSH with SourceTree and GitHub (scroll down to the "Method 2: Connect with SSH Key" section)
