### ISSUE TITLE
Unable to push due to authentication error

### ISSUE THREAD

**Issue by jjiayyingtt** [nus-cs2103-AY2223S2/forum#74]
I have used personal authentication token to add my account on sourcetree. But when I try to push, I am still getting the same error. 
![image](https://user-images.githubusercontent.com/89056416/215010611-112667a6-5768-4042-8ff9-bd4a701cbeae.png)

I've also looked online but can't seem to find a solution.

**Comment by Nafeij** [comment]
Try the following steps:

1. In Sourcetree, navigate `Settings (Repository settings) ->Remotes -> Select Origin ->  Edit`
2. Set URL/Path in the following format:  `https://<TOKEN>@<GIT_URL>.git`

P.S> Next time, [please provide more details :)](https://github.com/nus-cs2103-AY2223S2/forum/blob/master/.github/ISSUE_TEMPLATE/help.md). Also, when posting an error or stack trace, please Copy-Paste it as text instead of a screenshot so that it is searchable.

**Comment by jjiayyingtt** [comment]
> 

That worked, thank you :) I'll also take note of my forum posts in the future!
