### ISSUE TITLE
Query about Application.launch() in using JavaFX

### ISSUE THREAD

**Issue by heeeyi** [nus-cs2103-AY2223S2/forum#76]
Hi I have been studying about JavaFX following strictly to this tutorial. https://se-education.org/guides/tutorials/javaFxPart1.html

I found that following Tutorial 1, when I stried to add the start() method to my own Duke engine and use Launcher to launch it, the program always complains about "Unable to construct Applicaiton instance". This is the code for the launcher:

public class Launcher {
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}

I did some self-research and found out the cause is that the only constructor I have for Duke is Duke(String filepath), while the Application.launch() code for Launcher assumes a constructor Duke(). Indeed, when I added a dummy Duke() to the code, the issue resolves. However, I am not sure if this is the optimal way, since the dummy Duke() is not supposed to be in the project.

My question: How can I tell Application.launch() to take Duke(String filePath) instead of Duke() when creating instance? Or is there any other way around?

![屏幕截图(1435)](https://user-images.githubusercontent.com/97591125/215042791-38666769-3331-46d6-87a8-981dfa090150.png)

**Comment by Nafeij** [comment]
@heeeyi
The JavaFX runtime instantiates an instance of your Application subclass using reflection. It does this by assuming and using the public no-arg constructor of the class. Since it's baked into the base class's design, there are no two ways about it: you need a `public Duke()` constructor.
However, I understand your concerns about code quality w.r.t just supplying a dummy constructor. Perhaps you could put the empty constructor to use by calling the overloaded constructor with a default value?

``` java
public static final DEFAULT_PATH = "data.txt";
...
public Duke() {
    this(DEFAULT_PATH);
}
```

**Comment by hansstanley** [comment]
@heeeyi 

Alternatively, as you'll see in the [JavaFX tutorial part 4](https://se-education.org/guides/tutorials/javaFxPart4.html), you can create a `Main` class that extends `Application`, and create an instance of `Duke` in `Main`, for e.g.

```java
public class Main extends Application {
    private Duke duke = new Duke("data.txt");
    // ...
}
```

Then the `Launcher` class becomes

```java
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}
```

**Comment by damithc** [comment]
@heeeyi is the issue resolved?

**Comment by EmilyOng** [comment]
Hello @heeeyi, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Hopefully, your issue is resolved! One tip in making GitHub issues is that you can use the code-fencing syntax like so:

````
```java
public class Launcher {
  public static void main(String[] args) {
    Application.launch(Duke.class, args);
  }
}
```
````

This lets you have formatted code blocks which improves readability:

```java
public class Launcher {
  public static void main(String[] args) {
    Application.launch(Duke.class, args);
  }
}
```
