### ISSUE TITLE
Fixing corrupted fonts in AB3 - Unable to find and delete Java 17.0.1 on my mac

### ISSUE THREAD

**Issue by ChangGittyHub** [nus-cs2103-AY2223S2/forum#78]
java --version indicated I have java 17.0.1 on my computer
So I downloaded zulu 11 and followed the video to delete java 17.0.1 on my mac but I could not find java 17.0.1 under JavaVirtualMachine folder as shown in my screenshot.
Anyone knows how I can find and delete java 17.0.1 on my mac?

<img width="496" alt="Screen Shot 2023-01-27 at 9 16 55 PM" src="https://user-images.githubusercontent.com/82028822/215096009-3dc4b854-bafb-4f75-82ba-85266839db69.png">
<img width="530" alt="Screen Shot 2023-01-27 at 9 18 49 PM" src="https://user-images.githubusercontent.com/82028822/215096430-13cfe315-3e7d-4abd-8a7e-3739f3bf0286.png">

**Comment by RubyNguyen07** [comment]
@ChangGittyHub Hello, in my case i did a few random things and the openjdk version (that did not exist before) suddenly popped up. Then i deleted that version and it worked. After that I did some research and I think you could try cd into the /Library/Java directory then type "sudo rm -fr JavaVirtualMachines/*" to delete all Java versions.  Let me know if it works!

**Comment by jiexuanc** [comment]
@ChangGittyHub The JDK might be in ~/Library/Java/JavaVirtualMachines instead of /Library/Java/JavaVirtualMachines

**Comment by 4ndrelim** [comment]
@ChangGittyHub Hi, i actually had the same issue on my mac. I had both openjdk 11.0.11 (From CS2040S) and java 17..0.1 which was the default before i switched to java 11. 

On my terminal, i simply did `export JAVA_HOME='/usr/libexec/java_home -v 11.0'` and the switch was done. Naturally, you must have java 11 installed for the command to work. This [link](https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a) is a comprehensive but succinct guide to what i've described above, including how to check if you have the right version installed.

If you need more help, perhaps can check out this [link](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos) as well. It says pretty much the same thing, with some additional errors users may face.

Edit: Some issues with having backticks in backticks, note that `/usr/libexec/java_home -v 11.0` should be encapsulated in backticks instead of quotations.

**Comment by huanghao1998** [comment]
@ChangGittyHub Hi, I have found this [link](https://stackoverflow.com/questions/18144660/what-is-path-of-jdk-on-mac) which might be useful. 
```
/usr/libexec/java_home
```
Running this command might indicate where ur JDK located at. 

Hope it is helpful to you!

**Comment by ChangGittyHub** [comment]
Wow thanks so much.super appreciate it... I found it in ~/Library/Java/JavaVirtualMachines and deleted all versions which solved the problem! Thanks!!

**Comment by EvitanRelta** [comment]
> Wow thanks so much.super appreciate it... I found it in ~/Library/Java/JavaVirtualMachines and deleted all versions which solved the problem! Thanks!!

@ChangGittyHub, rmb to close the issue since it's solved 👌
