### ISSUE TITLE
Gradle stopped working suddenly

### ISSUE THREAD

**Issue by jerome-neo** [nus-cs2103-AY2223S2/forum#79]
I'm running duke on Intellij and have managed to integrate the Gradle support before. Just recently, I was running my Duke.java file again and this error suddenly popped up.

```
An exception occurred applying plugin request [id: 'com.github.johnrengelman.shadow', version: '5.1.0']
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin']
   > Could not create service of type OutputFilesRepository using ExecutionGradleServices.createOutputFilesRepository().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
Does anyone know what could be the reason for this error?

**Comment by Junyi00** [comment]
Running the gradle task with the options `--stacktrace` and/or `--debug` could be helpful to understand the root cause of the problem. You could try to do so and update here with its outputs.

My guess would be that there is some permission issue accessing your files, maybe some `.lock` files exist is preventing gradle from accessing them.

**Comment by LeonardYam** [comment]
There might be an issue with your build.gradle file - what does it look like?

There should be a plugin like so in your build.gradle file

``` 
plugins {
    id 'com.github.johnrengel.......'
}
```

**Comment by hingen** [comment]
Looking around on forums, it seems that it could be caused by a rogue gradle process running in the background or a gradle task not cleaning up after itself properly upon exiting leading to some `.lock` files being left behind.

Perhaps you could try:
1.  Restarting your computer to get rid of any rogue gradle processes. 
2. If it still does not work, push all your local changes to your remote repo, then clone the remote repo to a new local directory. This will get rid of the files mentioned in your `.gitignore` such as the `.gradle` directory and thus allow you to generate a new `.gradle` directory which would hopefully fix the issue if it was caused by a gradle task not properly cleaning up after itself.

**Comment by jerome-neo** [comment]
Thank you all for your input and explanations! It seems that restarting my computer resolved the issue.
