### ISSUE TITLE
JavaFX dependency issue

### ISSUE THREAD

**Issue by wengkit1** [nus-cs2103-AY2223S2/forum#85]
I'm using the community version of intelliJ. And I am having trouble using the javaFX packages.
I've done the relevant setup steps with the build gradle file but my when I try to compile my Ui class it does not seem to recognise the javaFX packages that were downloaded, despite being added to my dependencies.
Attached is my build.gradle file and the relevant error messages.
Also to note is that, intelliJ does not highlight any import issues with the imports for the relevant javaFX tools.
 
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/90920273/215287677-0c66cb8f-3343-435a-b2a3-2217d9d04ebc.png">

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try:
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
* Push the code to a branch and share here so that other can try to replicate the problem.

**Comment by Junyi00** [comment]
A quick trick that worked me was to click `Reload All Gradle Projects` in the Gradle toolbar.  
This should parse the `build.gradle` file and install the necessary dependencies.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/54541329/215457289-10d4e947-e1cf-49c2-99ba-03f23f987e7e.png">

**Comment by wengkit1** [comment]
Thanks for the help, turns out it was a rather silly mistake. When I run from command line on mac, the default version is open-jdk 19 which does not have javafx. I did not think i had the problem as I had previously removed the two jdks and used zulu build on mac, but somehow or rather, when i access the directory on command line, the two jdks are still there. 
It was a problem with my java_home variable. Thanks I learnt alot. But could someone explain why that happens?
