### ISSUE TITLE
Regarding Java Coding Standards

### ISSUE THREAD

**Issue by MrTwit99** [nus-cs2103-AY2223S2/forum#86]
Is it alright if I add a method within the main method and halfway through the code and not at the start or end of the code? 
Or would it be better if i move the method to the end of the main method instead? 
Main reason as to why my method is within the main method as I want to make use of some of the functions: PrintWriter and StringBuilder.

An image is shown below as to what I'm trying to describe.
![image](https://user-images.githubusercontent.com/97277438/215311026-8bcb4bad-b9b7-4d59-bc21-98c1df867ce5.png)

**Comment by hingen** [comment]
Don't think Java supports nested methods. If you want to do something like that, you would have to use a lambda expression
```java
// Declaration
Runnable messagePrinter = () -> {
    pw.println(sb.toString());
    pw.flush();
    sb.setLength(0);
};

// Call
messagePrinter.run()
```

Some additional info about lambda can be found here:
[Guide for Java lambda expressions](https://www.w3schools.com/java/java_lambda.asp)
[List of functional interfaces that can be used with lambda](https://www.educative.io/answers/a-list-of-all-the-functional-interfaces-in-java)

This is just my opinion, but I don't really like using lambdas in such a manner. I feel that it adds unnecessary nesting which can make code difficult to read and also has a tendency to make one method contain multiple layers of abstraction (which would violate the module's java coding standards). 

Perhaps consider:
1. Making variables like `pw` and `sb` class level variables (static variables) so that you would be able to use them in other class level methods inside the `main` class
2. Pass `pw` and `sb` as parameters into the `printMessage` method

**Comment by MrTwit99** [comment]
Thanks a lot @hingen! I think that helps with my issue!
