### ISSUE TITLE
Issue with Gradle setup 

### ISSUE THREAD

**Issue by 0x787af25e** [nus-cs2103-AY2223S2/forum#89]
I am facing problems after installing Gradle, where new changes to my program are ignored. When I type in code, these new lines of code are not executed; the debugger also stops at lines that are empty as those lines were populated with code before I added in new lines of code.

My `build.gradle` file:
`
plugins {
    id 'java'
    id 'application'
}
`
I am able to successfully build with Gradle.
![image](https://user-images.githubusercontent.com/74492257/215315004-94a2ba76-7f86-451e-a081-f760daf52db0.png)

I am running OpenJDK 17.0.3.

**Comment by damithc** [comment]
> I am running OpenJDK 17.0.3.

Oh? See https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html#:~:text=We%20require%20you%20to%20use%20Java%2011

**Comment by 0x787af25e** [comment]
![image](https://user-images.githubusercontent.com/74492257/215330369-b9ce62e5-a391-4c79-9fc3-446e844f633b.png)
Issue still persists after switching over to Java version 11.

**Comment by hingen** [comment]
@0x787af25e, may I know what is your full `build.gradle` file?

> I am able to successfully build with Gradle.

Also, may I check what you mean by successfully build? To build the app using gradle, the command should be `gradlew build`. The `gradlew` command only displays information about gradle, it doesn't actually build your app.

**Comment by 0x787af25e** [comment]
![image](https://user-images.githubusercontent.com/74492257/215331043-8e43a9d8-3c3e-4bec-9119-69b249fb26c3.png)
This is all there is, as mentioned above.

**Comment by hingen** [comment]
I see, I'm guessing that this was generated using `gradle init`?

Perhaps, instead of initialising gradle from scratch, try merging the `add-gradle-support` branch into `master`. This should get you the correct `build.gradle` file which should contain a lot more settings then the one you currently have. Can refer to the guide [here](https://se-education.org/guides/tutorials/gradle.html).

![image](https://user-images.githubusercontent.com/31367001/215331316-65a758d5-b8e2-439f-b1b6-1b7c8ac41993.png)
