### ISSUE TITLE
Regarding A-Jar / JAR file

### ISSUE THREAD

**Issue by MrTwit99** [nus-cs2103-AY2223S2/forum#93]
I managed to create the JAR file by following the steps shown in the video in this website: https://se-education.org/guides/tutorials/jar.html

However, as I try to run my Duke via the command java -jar (absolute file path), my Duke managed to startup but its file reading and writing capabilities are disabled. I suppose the issue here is the JAR file does not contain my file / shifted my file location hence causing this issue. Anyone else facing this issue and any tips on fixing this? 

![image](https://user-images.githubusercontent.com/97277438/215357790-cd43d733-2eb6-4b4c-808d-6ebad422e1e3.png)

**Comment by hingen** [comment]
Hi @MrTwit99. This is line 56 of your `Duke.java`:
```java
fileTasks = getFileContents("data/storage.txt", "data");
```

Java interprets `data/storage.txt` as a relative path (treats it the same as `./data/storage.txt`. This means that the actual full path is dependent on where the app is run from. Previously, you've likely always ran it from your `<project_root>` directory and hence the path is resolved to `<project_root>\data\storage.txt`.

In the screenshot provided, you are now attempting to run the app from `C:\Users\<name>` hence the path now resolves to `C:\Users\<name>\data\storage.txt` which does not exist.

Since it is not viable to always assume that `./data/storage.txt` always exist, it is better to create it at the start of the app if it is detected to not be there. This is also one of the requirements of the project.
![image](https://user-images.githubusercontent.com/31367001/215362766-54d654de-6cc3-4193-a076-5a3bb386cb79.png)

Also note that the project allows you to make the following assumptions:
![image](https://user-images.githubusercontent.com/31367001/215362841-8385bd0f-3744-4b5c-88a6-0c94990e0430.png)

**Comment by damithc** [comment]
> Also note that the project allows you to make the following assumptions:
> ![image](https://user-images.githubusercontent.com/31367001/215362841-8385bd0f-3744-4b5c-88a6-0c94990e0430.png)

@hingen is right. Thanks for the detailed reply.
@MrTwit99 you can follow the same scenario when you test the JAR file. And yes, consider creating the folder/file automatically if it doesn't exist yet.

**Comment by MrTwit99** [comment]
Thanks @hingen and prof!
